// Generated by `wit-bindgen` 0.61.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     wasi:io@0.2.0
//     wasi:cli@0.2.0
//     wasi:clocks@0.2.0
//     wasi:random@0.2.0
//     portfolio:value@0.1.0

package wasi_cli_stdin

import (
	"wit_component/wasi_io_streams"
)

type InputStream = wasi_io_streams.InputStream

//go:wasmimport wasi:cli/stdin@0.2.0 get-stdin
func wasm_import_get_stdin() int32

func GetStdin() *wasi_io_streams.InputStream {

	result := wasm_import_get_stdin()
	return wasi_io_streams.InputStreamFromOwnHandle(int32(uintptr(result)))

}
