[package]
name = "real-estate-escrow-domain"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
guestfmt = { path = "../guestfmt" }
guestio = { path = "../guestio" }
wit-bindgen = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
