// Generated by `wit-bindgen` 0.61.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     wasi:io@0.2.0
//     wasi:cli@0.2.0
//     wasi:clocks@0.2.0
//     wasi:random@0.2.0
//     price:history@0.1.0

package main

import (
	witRuntime "go.bytecodealliance.org/pkg/wit/runtime"
	witTypes "go.bytecodealliance.org/pkg/wit/types"
	"runtime"
	"unsafe"
	"wit_component/export_price_history_history"
	"wit_component/price_history_history"
)

var staticPinner = runtime.Pinner{}
var exportReturnArea = uintptr(witRuntime.Allocate(&staticPinner, (40 + 4*4), 8))
var syncExportPinner = runtime.Pinner{}

//go:wasmexport price:history/history@0.1.0#at
func wasm_export_price_history_history_at(arg0 uintptr, arg1 uint32, arg2 int32, arg3 int64) uintptr {

	pinner := &syncExportPinner
	result := make([]price_history_history.Quote, 0, arg1)
	for index := 0; index < int(arg1); index++ {
		base := unsafe.Add(unsafe.Pointer(arg0), index*(24+4*4))
		value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))))
		value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 3*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 4*4))))

		result = append(result, price_history_history.Quote{UnitMinor: *(*int64)(unsafe.Add(unsafe.Pointer(base), 0)), Currency: value, Kind: uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 2*4))))), Source: value0, At: uint64(*(*int64)(unsafe.Add(unsafe.Pointer(base), (16 + 4*4))))})
	}

	witRuntime.Unpin()
	result1 := export_price_history_history.At(result, uint8(arg2), uint64(arg3))

	switch result1.Tag() {
	case witTypes.ResultOk:
		payload := result1.Ok()
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(0))
		*(*int64)(unsafe.Add(unsafe.Pointer(exportReturnArea), 8)) = (payload).UnitMinor
		utf8 := unsafe.Pointer(unsafe.StringData((payload).Currency))
		pinner.Pin(utf8)
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (16 + 1*4))) = uint32(uint32(len((payload).Currency)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 16)) = uint32(uintptr(uintptr(utf8)))
		utf82 := unsafe.Pointer(unsafe.StringData((payload).Source))
		pinner.Pin(utf82)
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (16 + 3*4))) = uint32(uint32(len((payload).Source)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (16 + 2*4))) = uint32(uintptr(uintptr(utf82)))
		*(*int64)(unsafe.Add(unsafe.Pointer(exportReturnArea), (16 + 4*4))) = int64((payload).ObservedAt)
		*(*int64)(unsafe.Add(unsafe.Pointer(exportReturnArea), (24 + 4*4))) = int64((payload).AgeSeconds)
		var result3 int32
		if (payload).Carried {
			result3 = 1
		} else {
			result3 = 0
		}
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), (32 + 4*4))) = int8(result3)

	case witTypes.ResultErr:
		payload := result1.Err()
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(1))

		switch payload.Tag() {
		case price_history_history.PriceErrorNotYetPriced:

			*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 8)) = int8(int32(0))

		case price_history_history.PriceErrorMixedCurrency:
			payload := payload.MixedCurrency()
			*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 8)) = int8(int32(1))
			utf84 := unsafe.Pointer(unsafe.StringData((payload).F0))
			pinner.Pin(utf84)
			*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (8 + 2*4))) = uint32(uint32(len((payload).F0)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (8 + 1*4))) = uint32(uintptr(uintptr(utf84)))
			utf85 := unsafe.Pointer(unsafe.StringData((payload).F1))
			pinner.Pin(utf85)
			*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (8 + 4*4))) = uint32(uint32(len((payload).F1)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (8 + 3*4))) = uint32(uintptr(uintptr(utf85)))

		case price_history_history.PriceErrorZeroStep:

			*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 8)) = int8(int32(2))

		default:
			panic("unreachable")
		}

	default:
		panic("unreachable")
	}
	return exportReturnArea

}

//go:wasmexport cabi_post_price:history/history@0.1.0#at
func wasm_export_post_return_price_history_history_at(result uintptr) {
	syncExportPinner.Unpin()
}

//go:wasmexport price:history/history@0.1.0#series
func wasm_export_price_history_history_series(arg0 uintptr, arg1 uint32, arg2 int32, arg3 int64, arg4 int64, arg5 int64) uintptr {

	pinner := &syncExportPinner
	result := make([]price_history_history.Quote, 0, arg1)
	for index := 0; index < int(arg1); index++ {
		base := unsafe.Add(unsafe.Pointer(arg0), index*(24+4*4))
		value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))))
		value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 3*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 4*4))))

		result = append(result, price_history_history.Quote{UnitMinor: *(*int64)(unsafe.Add(unsafe.Pointer(base), 0)), Currency: value, Kind: uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 2*4))))), Source: value0, At: uint64(*(*int64)(unsafe.Add(unsafe.Pointer(base), (16 + 4*4))))})
	}

	witRuntime.Unpin()
	result1 := export_price_history_history.Series(result, uint8(arg2), uint64(arg3), uint64(arg4), uint64(arg5))

	switch result1.Tag() {
	case witTypes.ResultOk:
		payload := result1.Ok()
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(0))
		slice := payload
		length := uint32(len(slice))
		result3 := witRuntime.Allocate(pinner, uintptr(length*24), 8)
		for index, element := range slice {
			base := unsafe.Add(result3, index*24)
			*(*int64)(unsafe.Add(unsafe.Pointer(base), 0)) = int64((element).At)
			*(*int64)(unsafe.Add(unsafe.Pointer(base), 8)) = (element).UnitMinor
			var result2 int32
			if (element).Carried {
				result2 = 1
			} else {
				result2 = 0
			}
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 16)) = int8(result2)

		}

		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (2 * 4))) = uint32(length)
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 4)) = uint32(uintptr(uintptr(result3)))

	case witTypes.ResultErr:
		payload := result1.Err()
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(1))

		switch payload.Tag() {
		case price_history_history.PriceErrorNotYetPriced:

			*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 4)) = int8(int32(0))

		case price_history_history.PriceErrorMixedCurrency:
			payload := payload.MixedCurrency()
			*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 4)) = int8(int32(1))
			utf8 := unsafe.Pointer(unsafe.StringData((payload).F0))
			pinner.Pin(utf8)
			*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (3 * 4))) = uint32(uint32(len((payload).F0)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (2 * 4))) = uint32(uintptr(uintptr(utf8)))
			utf84 := unsafe.Pointer(unsafe.StringData((payload).F1))
			pinner.Pin(utf84)
			*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (5 * 4))) = uint32(uint32(len((payload).F1)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (4 * 4))) = uint32(uintptr(uintptr(utf84)))

		case price_history_history.PriceErrorZeroStep:

			*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 4)) = int8(int32(2))

		default:
			panic("unreachable")
		}

	default:
		panic("unreachable")
	}
	return exportReturnArea

}

//go:wasmexport cabi_post_price:history/history@0.1.0#series
func wasm_export_post_return_price_history_history_series(result uintptr) {
	syncExportPinner.Unpin()
}

// Unused, but present to make the compiler happy
func main() {}
