//! Generate a static-asset table from `static/` (the built React SPA) so the
//! component can serve the UI itself — embedded in the wasm, no filesystem.
//! Emits `OUT_DIR/static_assets.rs`: `STATIC_ASSETS: &[(path, content_type,
//! &[u8])]`, each file `include_bytes!`'d.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

fn content_type(p: &Path) -> &'static str {
    match p.extension().and_then(|e| e.to_str()) {
        Some("html") => "text/html; charset=utf-8",
        Some("js") | Some("mjs") => "text/javascript; charset=utf-8",
        Some("css") => "text/css; charset=utf-8",
        Some("json") => "application/json",
        Some("svg") => "image/svg+xml",
        Some("woff2") => "font/woff2",
        Some("woff") => "font/woff",
        Some("png") => "image/png",
        Some("jpg") | Some("jpeg") => "image/jpeg",
        Some("ico") => "image/x-icon",
        _ => "application/octet-stream",
    }
}

fn walk(dir: &Path, root: &Path, out: &mut Vec<(String, PathBuf)>) {
    let Ok(entries) = std::fs::read_dir(dir) else { return };
    for e in entries.flatten() {
        let path = e.path();
        if path.is_dir() {
            walk(&path, root, out);
        } else {
            // web path: "/" + relative, forward slashes.
            let rel = path.strip_prefix(root).unwrap().to_string_lossy().replace('\\', "/");
            out.push((format!("/{rel}"), path));
        }
    }
}

fn main() {
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let static_dir = manifest.join("static");
    println!("cargo:rerun-if-changed=static");

    let mut files = Vec::new();
    if static_dir.is_dir() {
        walk(&static_dir, &static_dir, &mut files);
    }
    files.sort();

    let mut code = String::new();
    code.push_str("// @generated by build.rs — embedded SPA assets.\n");
    code.push_str("pub static STATIC_ASSETS: &[(&str, &str, &[u8])] = &[\n");
    for (web_path, fs_path) in &files {
        let ct = content_type(fs_path);
        // include_bytes! needs an absolute path literal.
        writeln!(
            code,
            "    ({:?}, {:?}, include_bytes!({:?})),",
            web_path, ct, fs_path.to_string_lossy()
        )
        .unwrap();
    }
    code.push_str("];\n");

    let out = PathBuf::from(std::env::var("OUT_DIR").unwrap()).join("static_assets.rs");
    std::fs::write(&out, code).unwrap();
}
