//! `track-assets` — the track (project tracker) SPA embedded as `ui:assets`.
//!
//! The built Vite+TS SPA embedded at build time (build.rs walks `static/` and
//! `include_bytes!`s every file). Its own component so track-domain stays slim
//! — it links this for `GET /`, `/assets/*` instead of carrying the UI bytes in
//! its own artifact, which inflates per-request instantiation on hosts that
//! instantiate per request (wasmCloud).
//!
//! Pure compute: exact-path lookup over a static table. No imports, no state.

#[allow(warnings)]
mod bindings;

// STATIC_ASSETS: &[(web_path, content_type, bytes)], generated by build.rs.
mod static_assets {
    include!(concat!(env!("OUT_DIR"), "/static_assets.rs"));
}

use bindings::exports::ui::assets::files::{Asset, Guest};

struct Component;

impl Guest for Component {
    fn get(path: String) -> Option<Asset> {
        static_assets::STATIC_ASSETS
            .iter()
            .find(|(p, _, _)| *p == path)
            .map(|(_, ct, bytes)| Asset { content_type: (*ct).to_string(), body: bytes.to_vec() })
    }
}

bindings::export!(Component with_types_in bindings);
