//! `grocery-assets` — the Grocery Shop React SPA embedded as `ui:assets`.
//!
//! The built Vite+React SPA embedded at build time (build.rs walks `static/` and
//! `include_bytes!`s every file).

#[allow(warnings)]
mod bindings;

// STATIC_ASSETS: &[(web_path, content_type, bytes)], generated by build.rs.
mod static_assets {
    include!(concat!(env!("OUT_DIR"), "/static_assets.rs"));
}

use bindings::exports::ui::assets::files::{Asset, Guest};

struct Component;

impl Guest for Component {
    fn get(path: String) -> Option<Asset> {
        static_assets::STATIC_ASSETS
            .iter()
            .find(|(p, _, _)| *p == path)
            .map(|(_, ct, bytes)| Asset {
                content_type: (*ct).to_string(),
                body: bytes.to_vec(),
            })
    }
}

bindings::export!(Component with_types_in bindings);
