// Generated by `wit-bindgen` 0.61.0. DO NOT EDIT!
// <auto-generated />
#nullable enable

using System;

namespace PortfolioValueWorld.wit.Exports.portfolio.value
{
    public static class ValuationExportsInterop {

        [global::System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(EntryPoint = "portfolio:value/valuation@0.1.0#value-at")]
        public static unsafe nint wasmExportValueAt(nint p0, int p1, nint p2, int p3, long p4) {

            var array = new global::System.Collections.Generic.List<global::PortfolioValueWorld.wit.Exports.portfolio.value.IValuationExports.Event>(p1);
            for (int index = 0; index < p1; ++index) {
                nint basePtr = p0 + (index * 40);

                var str = global::System.Text.Encoding.UTF8.GetString((byte*)new global::System.Span<nint>((void*)((byte*)basePtr + 0), 1)[0], new global::System.Span<int>((void*)((byte*)basePtr + 4), 1)[0]);
                if (new global::System.Span<int>((void*)((byte*)basePtr + 4), 1)[0] > 0) {
                    global::System.Runtime.InteropServices.NativeMemory.Free((void*)new global::System.Span<nint>((void*)((byte*)basePtr + 0), 1)[0]);
                }

                var str0 = global::System.Text.Encoding.UTF8.GetString((byte*)new global::System.Span<nint>((void*)((byte*)basePtr + 24), 1)[0], new global::System.Span<int>((void*)((byte*)basePtr + 28), 1)[0]);
                if (new global::System.Span<int>((void*)((byte*)basePtr + 28), 1)[0] > 0) {
                    global::System.Runtime.InteropServices.NativeMemory.Free((void*)new global::System.Span<nint>((void*)((byte*)basePtr + 24), 1)[0]);
                }

                array.Add(new global::PortfolioValueWorld.wit.Exports.portfolio.value.IValuationExports.Event (
                str, (global::PortfolioValueWorld.wit.Exports.portfolio.value.IValuationExports.EventKind)new global::System.Span<byte>((byte*)basePtr + 8, 1)[0], unchecked((uint)(new global::System.Span<int>((void*)((byte*)basePtr + 12), 1)[0])), new global::System.Span<long>((void*)((byte*)basePtr + 16), 1)[0], str0, unchecked((ulong)(new global::System.Span<long>((void*)((byte*)basePtr + 32), 1)[0]))));
            }

            if (p1 > 0) {
                global::System.Runtime.InteropServices.NativeMemory.Free((void*)p0);
            }

            var array7 = new global::System.Collections.Generic.List<global::PortfolioValueWorld.wit.Exports.portfolio.value.IValuationExports.Quote>(p3);
            for (int index8 = 0; index8 < p3; ++index8) {
                nint basePtr2 = p2 + (index8 * 32);

                var str5 = global::System.Text.Encoding.UTF8.GetString((byte*)new global::System.Span<nint>((void*)((byte*)basePtr2 + 0), 1)[0], new global::System.Span<int>((void*)((byte*)basePtr2 + 4), 1)[0]);
                if (new global::System.Span<int>((void*)((byte*)basePtr2 + 4), 1)[0] > 0) {
                    global::System.Runtime.InteropServices.NativeMemory.Free((void*)new global::System.Span<nint>((void*)((byte*)basePtr2 + 0), 1)[0]);
                }

                var str6 = global::System.Text.Encoding.UTF8.GetString((byte*)new global::System.Span<nint>((void*)((byte*)basePtr2 + 16), 1)[0], new global::System.Span<int>((void*)((byte*)basePtr2 + 20), 1)[0]);
                if (new global::System.Span<int>((void*)((byte*)basePtr2 + 20), 1)[0] > 0) {
                    global::System.Runtime.InteropServices.NativeMemory.Free((void*)new global::System.Span<nint>((void*)((byte*)basePtr2 + 16), 1)[0]);
                }

                array7.Add(new global::PortfolioValueWorld.wit.Exports.portfolio.value.IValuationExports.Quote (
                str5, new global::System.Span<long>((void*)((byte*)basePtr2 + 8), 1)[0], str6, unchecked((ulong)(new global::System.Span<long>((void*)((byte*)basePtr2 + 24), 1)[0]))));
            }

            if (p3 > 0) {
                global::System.Runtime.InteropServices.NativeMemory.Free((void*)p2);
            }
            Result<global::PortfolioValueWorld.wit.Exports.portfolio.value.IValuationExports.Valuation, global::PortfolioValueWorld.wit.Exports.portfolio.value.IValuationExports.ValueError> ret;

            try
            {

                ret = Result<global::PortfolioValueWorld.wit.Exports.portfolio.value.IValuationExports.Valuation, global::PortfolioValueWorld.wit.Exports.portfolio.value.IValuationExports.ValueError>.Ok(ValuationExportsImpl.ValueAt((array), (array7), (unchecked((ulong)(p4)))));
            }
            catch (WitException e)
            {
                switch (e.NestingLevel)
                {
                    case 0:
                    {
                        ret = Result<global::PortfolioValueWorld.wit.Exports.portfolio.value.IValuationExports.Valuation, global::PortfolioValueWorld.wit.Exports.portfolio.value.IValuationExports.ValueError>.Err((global::PortfolioValueWorld.wit.Exports.portfolio.value.IValuationExports.ValueError) e.Value);
                        break;
                    }

                    default: throw new global::System.ArgumentException($"invalid nesting level: {e.NestingLevel}");
                }
            }

            var ptr = InteropReturnArea.returnArea.AddressOfReturnArea();

            switch (ret.Tag) {
                case 0: {
                    global::PortfolioValueWorld.wit.Exports.portfolio.value.IValuationExports.Valuation payload = ret.AsOk;
                    *(byte*)(ptr + 0) = (byte)0;
                    new global::System.Span<long>((void*)((byte*)ptr + 8), 1)[0] = unchecked((long)payload.costBasisMinor);
                    new global::System.Span<long>((void*)((byte*)ptr + 16), 1)[0] = unchecked((long)payload.marketValueMinor);
                    new global::System.Span<long>((void*)((byte*)ptr + 24), 1)[0] = unchecked((long)payload.unrealisedMinor);
                    new global::System.Span<long>((void*)((byte*)ptr + 32), 1)[0] = unchecked((long)payload.realisedMinor);

                    var stringSpan = global::System.MemoryExtensions.AsSpan(payload.currency);
                    var length = global::System.Text.Encoding.UTF8.GetByteCount(stringSpan);
                    var strPtr = global::System.Runtime.InteropServices.NativeMemory.Alloc((nuint)length);
                    global::System.Text.Encoding.UTF8.GetBytes(stringSpan, new global::System.Span<byte>(strPtr, length));

                    new global::System.Span<int>((void*)((byte*)ptr + 44), 1)[0] = length;
                    new global::System.Span<nint>((void*)((byte*)ptr + 40), 1)[0] = (nint)(int)strPtr;
                    new global::System.Span<int>((void*)((byte*)ptr + 48), 1)[0] = unchecked((int)(payload.unquoted));

                    break;
                }
                case 1: {
                    global::PortfolioValueWorld.wit.Exports.portfolio.value.IValuationExports.ValueError payload17 = ret.AsErr;
                    *(byte*)(ptr + 0) = (byte)1;

                    switch (payload17.Tag) {
                        case 0: {
                            (string, string) payload22 = payload17.AsMixedCurrency;
                            *(byte*)(ptr + 8) = (byte)0;

                            var stringSpan27 = global::System.MemoryExtensions.AsSpan(payload22.Item1);
                            var length25 = global::System.Text.Encoding.UTF8.GetByteCount(stringSpan27);
                            var strPtr23 = global::System.Runtime.InteropServices.NativeMemory.Alloc((nuint)length25);
                            global::System.Text.Encoding.UTF8.GetBytes(stringSpan27, new global::System.Span<byte>(strPtr23, length25));

                            new global::System.Span<int>((void*)((byte*)ptr + 20), 1)[0] = length25;
                            new global::System.Span<nint>((void*)((byte*)ptr + 16), 1)[0] = (nint)(int)strPtr23;

                            var stringSpan32 = global::System.MemoryExtensions.AsSpan(payload22.Item2);
                            var length30 = global::System.Text.Encoding.UTF8.GetByteCount(stringSpan32);
                            var strPtr28 = global::System.Runtime.InteropServices.NativeMemory.Alloc((nuint)length30);
                            global::System.Text.Encoding.UTF8.GetBytes(stringSpan32, new global::System.Span<byte>(strPtr28, length30));

                            new global::System.Span<int>((void*)((byte*)ptr + 28), 1)[0] = length30;
                            new global::System.Span<nint>((void*)((byte*)ptr + 24), 1)[0] = (nint)(int)strPtr28;

                            break;
                        }
                        case 1: {
                            (string, ulong, uint, uint) payload37 = payload17.AsOversoldAt;
                            *(byte*)(ptr + 8) = (byte)1;

                            var stringSpan42 = global::System.MemoryExtensions.AsSpan(payload37.Item1);
                            var length40 = global::System.Text.Encoding.UTF8.GetByteCount(stringSpan42);
                            var strPtr38 = global::System.Runtime.InteropServices.NativeMemory.Alloc((nuint)length40);
                            global::System.Text.Encoding.UTF8.GetBytes(stringSpan42, new global::System.Span<byte>(strPtr38, length40));

                            new global::System.Span<int>((void*)((byte*)ptr + 20), 1)[0] = length40;
                            new global::System.Span<nint>((void*)((byte*)ptr + 16), 1)[0] = (nint)(int)strPtr38;
                            new global::System.Span<long>((void*)((byte*)ptr + 24), 1)[0] = unchecked((long)unchecked((long)(payload37.Item2)));
                            new global::System.Span<int>((void*)((byte*)ptr + 32), 1)[0] = unchecked((int)(payload37.Item3));
                            new global::System.Span<int>((void*)((byte*)ptr + 36), 1)[0] = unchecked((int)(payload37.Item4));

                            break;
                        }
                        case 2: {
                            (string, ulong) payload47 = payload17.AsZeroQuantity;
                            *(byte*)(ptr + 8) = (byte)2;

                            var stringSpan52 = global::System.MemoryExtensions.AsSpan(payload47.Item1);
                            var length50 = global::System.Text.Encoding.UTF8.GetByteCount(stringSpan52);
                            var strPtr48 = global::System.Runtime.InteropServices.NativeMemory.Alloc((nuint)length50);
                            global::System.Text.Encoding.UTF8.GetBytes(stringSpan52, new global::System.Span<byte>(strPtr48, length50));

                            new global::System.Span<int>((void*)((byte*)ptr + 20), 1)[0] = length50;
                            new global::System.Span<nint>((void*)((byte*)ptr + 16), 1)[0] = (nint)(int)strPtr48;
                            new global::System.Span<long>((void*)((byte*)ptr + 24), 1)[0] = unchecked((long)unchecked((long)(payload47.Item2)));

                            break;
                        }
                        case 3: {

                            *(byte*)(ptr + 8) = (byte)3;

                            break;
                        }
                        case 4: {

                            *(byte*)(ptr + 8) = (byte)4;

                            break;
                        }

                        default: throw new global::System.ArgumentException("invalid discriminant: " + payload17);
                    }

                    break;
                }

                default: throw new global::System.ArgumentException("invalid discriminant: " + ret);
            }
            return ptr;

        }

        [global::System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(EntryPoint = "cabi_post_portfolio:value/valuation@0.1.0#value-at")]
        public static unsafe void cabi_post_wasmExportValueAt(nint p0) {

            switch (new global::System.Span<byte>((byte*)p0 + 0, 1)[0]) {
                case 0: {
                    global::System.Runtime.InteropServices.NativeMemory.Free((void*)new global::System.Span<nint>((void*)((byte*)p0 + 40), 1)[0]);

                    break;
                }
                case 1: {

                    switch (new global::System.Span<byte>((byte*)p0 + 8, 1)[0]) {
                        case 0: {
                            global::System.Runtime.InteropServices.NativeMemory.Free((void*)new global::System.Span<nint>((void*)((byte*)p0 + 16), 1)[0]);
                            global::System.Runtime.InteropServices.NativeMemory.Free((void*)new global::System.Span<nint>((void*)((byte*)p0 + 24), 1)[0]);

                            break;
                        }
                        case 1: {
                            global::System.Runtime.InteropServices.NativeMemory.Free((void*)new global::System.Span<nint>((void*)((byte*)p0 + 16), 1)[0]);

                            break;
                        }
                        case 2: {
                            global::System.Runtime.InteropServices.NativeMemory.Free((void*)new global::System.Span<nint>((void*)((byte*)p0 + 16), 1)[0]);

                            break;
                        }
                        case 3: {

                            break;
                        }
                        case 4: {

                            break;
                        }
                    }

                    break;
                }
            }

        }

        [global::System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(EntryPoint = "portfolio:value/valuation@0.1.0#series")]
        public static unsafe nint wasmExportSeries(nint p0, int p1, nint p2, int p3, long p4, long p5, long p6) {

            var array = new global::System.Collections.Generic.List<global::PortfolioValueWorld.wit.Exports.portfolio.value.IValuationExports.Event>(p1);
            for (int index = 0; index < p1; ++index) {
                nint basePtr = p0 + (index * 40);

                var str = global::System.Text.Encoding.UTF8.GetString((byte*)new global::System.Span<nint>((void*)((byte*)basePtr + 0), 1)[0], new global::System.Span<int>((void*)((byte*)basePtr + 4), 1)[0]);
                if (new global::System.Span<int>((void*)((byte*)basePtr + 4), 1)[0] > 0) {
                    global::System.Runtime.InteropServices.NativeMemory.Free((void*)new global::System.Span<nint>((void*)((byte*)basePtr + 0), 1)[0]);
                }

                var str0 = global::System.Text.Encoding.UTF8.GetString((byte*)new global::System.Span<nint>((void*)((byte*)basePtr + 24), 1)[0], new global::System.Span<int>((void*)((byte*)basePtr + 28), 1)[0]);
                if (new global::System.Span<int>((void*)((byte*)basePtr + 28), 1)[0] > 0) {
                    global::System.Runtime.InteropServices.NativeMemory.Free((void*)new global::System.Span<nint>((void*)((byte*)basePtr + 24), 1)[0]);
                }

                array.Add(new global::PortfolioValueWorld.wit.Exports.portfolio.value.IValuationExports.Event (
                str, (global::PortfolioValueWorld.wit.Exports.portfolio.value.IValuationExports.EventKind)new global::System.Span<byte>((byte*)basePtr + 8, 1)[0], unchecked((uint)(new global::System.Span<int>((void*)((byte*)basePtr + 12), 1)[0])), new global::System.Span<long>((void*)((byte*)basePtr + 16), 1)[0], str0, unchecked((ulong)(new global::System.Span<long>((void*)((byte*)basePtr + 32), 1)[0]))));
            }

            if (p1 > 0) {
                global::System.Runtime.InteropServices.NativeMemory.Free((void*)p0);
            }

            var array7 = new global::System.Collections.Generic.List<global::PortfolioValueWorld.wit.Exports.portfolio.value.IValuationExports.Quote>(p3);
            for (int index8 = 0; index8 < p3; ++index8) {
                nint basePtr2 = p2 + (index8 * 32);

                var str5 = global::System.Text.Encoding.UTF8.GetString((byte*)new global::System.Span<nint>((void*)((byte*)basePtr2 + 0), 1)[0], new global::System.Span<int>((void*)((byte*)basePtr2 + 4), 1)[0]);
                if (new global::System.Span<int>((void*)((byte*)basePtr2 + 4), 1)[0] > 0) {
                    global::System.Runtime.InteropServices.NativeMemory.Free((void*)new global::System.Span<nint>((void*)((byte*)basePtr2 + 0), 1)[0]);
                }

                var str6 = global::System.Text.Encoding.UTF8.GetString((byte*)new global::System.Span<nint>((void*)((byte*)basePtr2 + 16), 1)[0], new global::System.Span<int>((void*)((byte*)basePtr2 + 20), 1)[0]);
                if (new global::System.Span<int>((void*)((byte*)basePtr2 + 20), 1)[0] > 0) {
                    global::System.Runtime.InteropServices.NativeMemory.Free((void*)new global::System.Span<nint>((void*)((byte*)basePtr2 + 16), 1)[0]);
                }

                array7.Add(new global::PortfolioValueWorld.wit.Exports.portfolio.value.IValuationExports.Quote (
                str5, new global::System.Span<long>((void*)((byte*)basePtr2 + 8), 1)[0], str6, unchecked((ulong)(new global::System.Span<long>((void*)((byte*)basePtr2 + 24), 1)[0]))));
            }

            if (p3 > 0) {
                global::System.Runtime.InteropServices.NativeMemory.Free((void*)p2);
            }
            Result<global::System.Collections.Generic.List<global::PortfolioValueWorld.wit.Exports.portfolio.value.IValuationExports.Point>, global::PortfolioValueWorld.wit.Exports.portfolio.value.IValuationExports.ValueError> ret;

            try
            {

                ret = Result<global::System.Collections.Generic.List<global::PortfolioValueWorld.wit.Exports.portfolio.value.IValuationExports.Point>, global::PortfolioValueWorld.wit.Exports.portfolio.value.IValuationExports.ValueError>.Ok(ValuationExportsImpl.Series((array), (array7), (unchecked((ulong)(p4))), (unchecked((ulong)(p5))), (unchecked((ulong)(p6)))));
            }
            catch (WitException e)
            {
                switch (e.NestingLevel)
                {
                    case 0:
                    {
                        ret = Result<global::System.Collections.Generic.List<global::PortfolioValueWorld.wit.Exports.portfolio.value.IValuationExports.Point>, global::PortfolioValueWorld.wit.Exports.portfolio.value.IValuationExports.ValueError>.Err((global::PortfolioValueWorld.wit.Exports.portfolio.value.IValuationExports.ValueError) e.Value);
                        break;
                    }

                    default: throw new global::System.ArgumentException($"invalid nesting level: {e.NestingLevel}");
                }
            }

            var ptr = InteropReturnArea.returnArea.AddressOfReturnArea();

            switch (ret.Tag) {
                case 0: {
                    global::System.Collections.Generic.List<global::PortfolioValueWorld.wit.Exports.portfolio.value.IValuationExports.Point> payload = ret.AsOk;
                    *(byte*)(ptr + 0) = (byte)0;

                    var bufferSize = 40 * (nuint)payload.Count;
                    void* address = global::System.Runtime.InteropServices.NativeMemory.AlignedAlloc(bufferSize, 8);

                    for (int index17 = 0; index17 < payload.Count; ++index17) {
                        global::PortfolioValueWorld.wit.Exports.portfolio.value.IValuationExports.Point element13 = payload[index17];
                        int basePtr14 = (int)address + (index17 * 40);
                        new global::System.Span<long>((void*)((byte*)basePtr14 + 0), 1)[0] = unchecked((long)unchecked((long)(element13.at)));
                        new global::System.Span<long>((void*)((byte*)basePtr14 + 8), 1)[0] = unchecked((long)element13.marketValueMinor);
                        new global::System.Span<long>((void*)((byte*)basePtr14 + 16), 1)[0] = unchecked((long)element13.costBasisMinor);
                        new global::System.Span<long>((void*)((byte*)basePtr14 + 24), 1)[0] = unchecked((long)element13.realisedMinor);
                        new global::System.Span<int>((void*)((byte*)basePtr14 + 32), 1)[0] = unchecked((int)(element13.unquoted));

                    }
                    new global::System.Span<int>((void*)((byte*)ptr + 12), 1)[0] = payload.Count;
                    new global::System.Span<nint>((void*)((byte*)ptr + 8), 1)[0] = (nint)(int)address;

                    break;
                }
                case 1: {
                    global::PortfolioValueWorld.wit.Exports.portfolio.value.IValuationExports.ValueError payload22 = ret.AsErr;
                    *(byte*)(ptr + 0) = (byte)1;

                    switch (payload22.Tag) {
                        case 0: {
                            (string, string) payload27 = payload22.AsMixedCurrency;
                            *(byte*)(ptr + 8) = (byte)0;

                            var stringSpan = global::System.MemoryExtensions.AsSpan(payload27.Item1);
                            var length = global::System.Text.Encoding.UTF8.GetByteCount(stringSpan);
                            var strPtr = global::System.Runtime.InteropServices.NativeMemory.Alloc((nuint)length);
                            global::System.Text.Encoding.UTF8.GetBytes(stringSpan, new global::System.Span<byte>(strPtr, length));

                            new global::System.Span<int>((void*)((byte*)ptr + 20), 1)[0] = length;
                            new global::System.Span<nint>((void*)((byte*)ptr + 16), 1)[0] = (nint)(int)strPtr;

                            var stringSpan32 = global::System.MemoryExtensions.AsSpan(payload27.Item2);
                            var length30 = global::System.Text.Encoding.UTF8.GetByteCount(stringSpan32);
                            var strPtr28 = global::System.Runtime.InteropServices.NativeMemory.Alloc((nuint)length30);
                            global::System.Text.Encoding.UTF8.GetBytes(stringSpan32, new global::System.Span<byte>(strPtr28, length30));

                            new global::System.Span<int>((void*)((byte*)ptr + 28), 1)[0] = length30;
                            new global::System.Span<nint>((void*)((byte*)ptr + 24), 1)[0] = (nint)(int)strPtr28;

                            break;
                        }
                        case 1: {
                            (string, ulong, uint, uint) payload37 = payload22.AsOversoldAt;
                            *(byte*)(ptr + 8) = (byte)1;

                            var stringSpan42 = global::System.MemoryExtensions.AsSpan(payload37.Item1);
                            var length40 = global::System.Text.Encoding.UTF8.GetByteCount(stringSpan42);
                            var strPtr38 = global::System.Runtime.InteropServices.NativeMemory.Alloc((nuint)length40);
                            global::System.Text.Encoding.UTF8.GetBytes(stringSpan42, new global::System.Span<byte>(strPtr38, length40));

                            new global::System.Span<int>((void*)((byte*)ptr + 20), 1)[0] = length40;
                            new global::System.Span<nint>((void*)((byte*)ptr + 16), 1)[0] = (nint)(int)strPtr38;
                            new global::System.Span<long>((void*)((byte*)ptr + 24), 1)[0] = unchecked((long)unchecked((long)(payload37.Item2)));
                            new global::System.Span<int>((void*)((byte*)ptr + 32), 1)[0] = unchecked((int)(payload37.Item3));
                            new global::System.Span<int>((void*)((byte*)ptr + 36), 1)[0] = unchecked((int)(payload37.Item4));

                            break;
                        }
                        case 2: {
                            (string, ulong) payload47 = payload22.AsZeroQuantity;
                            *(byte*)(ptr + 8) = (byte)2;

                            var stringSpan52 = global::System.MemoryExtensions.AsSpan(payload47.Item1);
                            var length50 = global::System.Text.Encoding.UTF8.GetByteCount(stringSpan52);
                            var strPtr48 = global::System.Runtime.InteropServices.NativeMemory.Alloc((nuint)length50);
                            global::System.Text.Encoding.UTF8.GetBytes(stringSpan52, new global::System.Span<byte>(strPtr48, length50));

                            new global::System.Span<int>((void*)((byte*)ptr + 20), 1)[0] = length50;
                            new global::System.Span<nint>((void*)((byte*)ptr + 16), 1)[0] = (nint)(int)strPtr48;
                            new global::System.Span<long>((void*)((byte*)ptr + 24), 1)[0] = unchecked((long)unchecked((long)(payload47.Item2)));

                            break;
                        }
                        case 3: {

                            *(byte*)(ptr + 8) = (byte)3;

                            break;
                        }
                        case 4: {

                            *(byte*)(ptr + 8) = (byte)4;

                            break;
                        }

                        default: throw new global::System.ArgumentException("invalid discriminant: " + payload22);
                    }

                    break;
                }

                default: throw new global::System.ArgumentException("invalid discriminant: " + ret);
            }
            return ptr;

        }

        [global::System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(EntryPoint = "cabi_post_portfolio:value/valuation@0.1.0#series")]
        public static unsafe void cabi_post_wasmExportSeries(nint p0) {

            switch (new global::System.Span<byte>((byte*)p0 + 0, 1)[0]) {
                case 0: {
                    global::System.Runtime.InteropServices.NativeMemory.Free((void*)new global::System.Span<nint>((void*)((byte*)p0 + 8), 1)[0]);

                    break;
                }
                case 1: {

                    switch (new global::System.Span<byte>((byte*)p0 + 8, 1)[0]) {
                        case 0: {
                            global::System.Runtime.InteropServices.NativeMemory.Free((void*)new global::System.Span<nint>((void*)((byte*)p0 + 16), 1)[0]);
                            global::System.Runtime.InteropServices.NativeMemory.Free((void*)new global::System.Span<nint>((void*)((byte*)p0 + 24), 1)[0]);

                            break;
                        }
                        case 1: {
                            global::System.Runtime.InteropServices.NativeMemory.Free((void*)new global::System.Span<nint>((void*)((byte*)p0 + 16), 1)[0]);

                            break;
                        }
                        case 2: {
                            global::System.Runtime.InteropServices.NativeMemory.Free((void*)new global::System.Span<nint>((void*)((byte*)p0 + 16), 1)[0]);

                            break;
                        }
                        case 3: {

                            break;
                        }
                        case 4: {

                            break;
                        }
                    }

                    break;
                }
            }

        }

    }
}
