// Generated by `wit-bindgen` 0.61.0. DO NOT EDIT!
// <auto-generated />
#nullable enable

namespace PortfolioValueWorld.wit.Exports.portfolio.value;

public interface IValuationExports {

    /**
    * What happened to an item, and when.
    *
    * A swap is two events, not one: what left is a disposal at the agreed value
    * and what arrived is an acquisition at that same value, so a trade where you
    * got the better end shows up as a gain.
    */

    public enum EventKind {
        ACQUIRED, DISPOSED
    }

    /**
    * One thing that happened to one item.
    */

    public struct Event {
        public string itemId;
        public EventKind kind;
        public uint quantity;
        public long unitMinor;
        public string currency;
        public ulong at;

        public Event(string itemId, EventKind kind, uint quantity, long unitMinor, string currency, ulong at) {
            this.itemId = itemId;
            this.kind = kind;
            this.quantity = quantity;
            this.unitMinor = unitMinor;
            this.currency = currency;
            this.at = at;
        }
    }

    /**
    * The latest known price for an item at some instant.
    */

    public struct Quote {
        public string itemId;
        public long unitMinor;
        public string currency;
        public ulong at;

        public Quote(string itemId, long unitMinor, string currency, ulong at) {
            this.itemId = itemId;
            this.unitMinor = unitMinor;
            this.currency = currency;
            this.at = at;
        }
    }

    /**
    * What a collection is worth, and how it got there.
    */

    public struct Valuation {
        public long costBasisMinor;
        public long marketValueMinor;
        public long unrealisedMinor;
        public long realisedMinor;
        public string currency;
        public uint unquoted;

        public Valuation(long costBasisMinor, long marketValueMinor, long unrealisedMinor, long realisedMinor, string currency, uint unquoted) {
            this.costBasisMinor = costBasisMinor;
            this.marketValueMinor = marketValueMinor;
            this.unrealisedMinor = unrealisedMinor;
            this.realisedMinor = realisedMinor;
            this.currency = currency;
            this.unquoted = unquoted;
        }
    }

    /**
    * One sample on the value chart.
    */

    public struct Point {
        public ulong at;
        public long marketValueMinor;
        public long costBasisMinor;
        public long realisedMinor;
        public uint unquoted;

        public Point(ulong at, long marketValueMinor, long costBasisMinor, long realisedMinor, uint unquoted) {
            this.at = at;
            this.marketValueMinor = marketValueMinor;
            this.costBasisMinor = costBasisMinor;
            this.realisedMinor = realisedMinor;
            this.unquoted = unquoted;
        }
    }

    /**
    * Why a valuation could not be produced. Every one of these is a silent wrong
    * number if it is absorbed instead of refused.
    */

    public class ValueError {
        public readonly byte Tag;
        private readonly object? value;

        private ValueError(byte tag, object? value) {
            this.Tag = tag;
            this.value = value;
        }

        public static ValueError MixedCurrency((string, string) mixedCurrency) {
            return new ValueError(Tags.MixedCurrency, mixedCurrency);
        }

        public static ValueError OversoldAt((string, ulong, uint, uint) oversoldAt) {
            return new ValueError(Tags.OversoldAt, oversoldAt);
        }

        public static ValueError ZeroQuantity((string, ulong) zeroQuantity) {
            return new ValueError(Tags.ZeroQuantity, zeroQuantity);
        }

        public static ValueError ZeroStep() {
            return new ValueError(Tags.ZeroStep, null);
        }

        public static ValueError Empty() {
            return new ValueError(Tags.Empty, null);
        }

        public (string, string) AsMixedCurrency
        {
            get
            {
                if (Tag == Tags.MixedCurrency)
                return ((string, string))value!;
                else
                throw new global::System.ArgumentException("expected MixedCurrency, got " + Tag);
            }
        }

        public (string, ulong, uint, uint) AsOversoldAt
        {
            get
            {
                if (Tag == Tags.OversoldAt)
                return ((string, ulong, uint, uint))value!;
                else
                throw new global::System.ArgumentException("expected OversoldAt, got " + Tag);
            }
        }

        public (string, ulong) AsZeroQuantity
        {
            get
            {
                if (Tag == Tags.ZeroQuantity)
                return ((string, ulong))value!;
                else
                throw new global::System.ArgumentException("expected ZeroQuantity, got " + Tag);
            }
        }

        public class Tags {
            public const byte MixedCurrency = 0;
            public const byte OversoldAt = 1;
            public const byte ZeroQuantity = 2;
            public const byte ZeroStep = 3;
            public const byte Empty = 4;
        }
    }
    static abstract global::PortfolioValueWorld.wit.Exports.portfolio.value.IValuationExports.Valuation ValueAt(global::System.Collections.Generic.List<global::PortfolioValueWorld.wit.Exports.portfolio.value.IValuationExports.Event> events, global::System.Collections.Generic.List<global::PortfolioValueWorld.wit.Exports.portfolio.value.IValuationExports.Quote> quotes, ulong at);

    static abstract global::System.Collections.Generic.List<global::PortfolioValueWorld.wit.Exports.portfolio.value.IValuationExports.Point> Series(global::System.Collections.Generic.List<global::PortfolioValueWorld.wit.Exports.portfolio.value.IValuationExports.Event> events, global::System.Collections.Generic.List<global::PortfolioValueWorld.wit.Exports.portfolio.value.IValuationExports.Quote> quotes, ulong since, ulong until, ulong step);

}
