// Generated by `wit-bindgen` 0.61.0. DO NOT EDIT!
// <auto-generated />
#nullable enable

using System;
using System.Runtime.InteropServices;
using System.Collections.Concurrent;
using System.Threading;
using System.Threading.Tasks;

namespace PortfolioValueWorld {

    public interface IPortfolioValueWorldImports{
    }

    public readonly struct None {}

    [global::System.Runtime.InteropServices.StructLayoutAttribute(global::System.Runtime.InteropServices.LayoutKind.Sequential)]
    public readonly struct Result<TOk, TErr>
    {
        public readonly byte Tag;
        private readonly object value;

        private Result(byte tag, object value)
        {
            Tag = tag;
            this.value = value;
        }

        public static Result<TOk, TErr> Ok(TOk ok)
        {
            return new Result<TOk, TErr>(Tags.Ok, ok!);
        }

        public static Result<TOk, TErr> Err(TErr err)
        {
            return new Result<TOk, TErr>(Tags.Err, err!);
        }

        public bool IsOk => Tag == Tags.Ok;
        public bool IsErr => Tag == Tags.Err;

        public TOk AsOk
        {
            get
            {
                if (Tag == Tags.Ok)
                {
                    return (TOk)value;
                }

                throw new global::System.ArgumentException("expected k, got " + Tag);
            }
        }

        public TErr AsErr
        {
            get
            {
                if (Tag == Tags.Err)
                {
                    return (TErr)value;
                }

                throw new global::System.ArgumentException("expected Err, got " + Tag);
            }
        }

        public class Tags
        {
            public const byte Ok = 0;
            public const byte Err = 1;
        }
    }

    public class WitException: global::System.Exception {
        public object Value { get; }
        public uint NestingLevel { get; }

        public WitException(object v, uint level)
        {
            Value = v;
            NestingLevel = level;
        }
    }

    public class WitException<T>: WitException {
        public T TypedValue { get { return (T)this.Value;} }

        public WitException(T v, uint level) : base(v!, level)
        {
        }
    }

    public static class InteropReturnArea
    {
        [global::System.Runtime.CompilerServices.InlineArrayAttribute(7)]
        [global::System.Runtime.InteropServices.StructLayoutAttribute(global::System.Runtime.InteropServices.LayoutKind.Sequential, Pack = 8)]
        internal struct ReturnArea
        {
            private ulong buffer;

            internal unsafe nint AddressOfReturnArea()
            {
                return (nint)global::System.Runtime.CompilerServices.Unsafe.AsPointer(ref buffer);
            }
        }

        [global::System.ThreadStaticAttribute]
        [global::System.Runtime.CompilerServices.FixedAddressValueTypeAttribute]
        internal static ReturnArea returnArea = default;
    }

    namespace Imports {
        public partial class PortfolioValueWorldImportsInterop : IPortfolioValueWorldImports
        {}
    }

}
