//! Site inspections: a principal files one, `overall_pass` is computed here
//! (never trusted from the request), the filer (or an admin) reads it back,
//! and the same pair may download it as a real PDF report.
//!
//! `admin` sees every inspection; an `inspector` only their own — the
//! row-level rule `auth:identity/rbac` cannot express, enforced per-row with
//! the same `guestauth::guest_owner_or_admin_policy!` macro `crm-domain` uses
//! for deal ownership, and at list time with the same `find_by` filter shape
//! as `crm-domain::list_deals`.

use crate::bindings::records::store::store as records;
use crate::bindings::wasi::http::types::Method;
use crate::{audit, introspect, is_admin, now_secs, Reply, Route};
use serde_json::{json, Value};

const POLICY_DOMAIN: &str = "inspections";

guestauth::guest_owner_or_admin_policy!(POLICY_DOMAIN, "inspector");
guestauth::guest_entries_json!();

pub fn handle(method: &Method, route: &Route, body: &str) -> Reply {
    let seg: Vec<&str> = route.segments.iter().map(String::as_str).collect();
    match (method, seg.as_slice()) {
        (Method::Post, ["api", "inspections"]) => create_inspection(route, body),
        (Method::Get, ["api", "inspections"]) => list_inspections(route),
        (Method::Get, ["api", "inspections", id]) => get_inspection(route, id),
        (Method::Get, ["api", "inspections", id, "pdf"]) => get_pdf(route, id),
        _ => Reply::err(404, "not_found"),
    }
}

/// The stored shape of an inspection, parsed back out of a
/// `records:store` entry's `data` JSON.
#[derive(serde::Deserialize, Default)]
struct StoredInspection {
    #[serde(default)]
    site_name: String,
    #[serde(default)]
    inspector: String,
    #[serde(default)]
    items: Vec<StoredItem>,
    #[serde(default)]
    overall_pass: bool,
    #[serde(default)]
    created: u64,
}

#[derive(serde::Deserialize, Default)]
struct StoredItem {
    #[serde(default)]
    label: String,
    #[serde(default)]
    pass: bool,
    #[serde(default)]
    note: String,
}

/// The request shape for filing an inspection.
#[derive(serde::Deserialize, Default)]
struct InspectionReq {
    #[serde(default)]
    site_name: String,
    #[serde(default)]
    items: Vec<StoredItem>,
}

/// One stored entry as a JSON document, its real record id merged in —
/// `entries_json` (generated by `guest_entries_json!`) for a single row.
fn one_json(entry: &records::Entry) -> Value {
    let mut v: Value = serde_json::from_str(&entry.data).unwrap_or_else(|_| json!({}));
    if let Value::Object(ref mut m) = v {
        m.insert("id".to_string(), json!(entry.id));
    }
    v
}

fn create_inspection(route: &Route, body: &str) -> Reply {
    let principal = guestauth::guest_authenticated!(route);
    let req = guestauth::guest_parse_body!(body, InspectionReq);
    if req.items.is_empty() {
        return Reply::err(400, "items is required");
    }
    let overall_pass = req.items.iter().all(|i| i.pass);
    let items: Vec<Value> = req
        .items
        .iter()
        .map(|i| json!({"label": i.label, "pass": i.pass, "note": i.note}))
        .collect();
    let data = json!({
        "org": principal.tenant,
        "inspector": principal.subject,
        "site_name": req.site_name,
        "items": items,
        "overall_pass": overall_pass,
        "status": "submitted",
        "created": now_secs(),
    })
    .to_string();
    match records::create("inspections", &data, &["inspector".to_string(), "org".to_string()]) {
        Ok(entry) => {
            audit("inspection.create", "allow", &principal.subject, &entry.id);
            Reply::json(
                201,
                json!({"id": entry.id, "overall_pass": overall_pass, "status": "submitted"}),
            )
        }
        Err(_) => Reply::err(500, "store_error"),
    }
}

fn list_inspections(route: &Route) -> Reply {
    let principal = guestauth::guest_authenticated!(route);
    let result = if is_admin(&principal) {
        records::list_records("inspections", 100, "").map(|p| p.entries)
    } else {
        let subject_json = serde_json::to_string(&principal.subject).unwrap_or_default();
        records::find_by("inspections", "inspector", &subject_json)
    };
    match result {
        Ok(entries) => Reply::json(200, json!({"inspections": entries_json(&entries)})),
        Err(_) => Reply::err(500, "store_error"),
    }
}

fn get_inspection(route: &Route, id: &str) -> Reply {
    let principal = guestauth::guest_authenticated!(route);
    // 404 first: a caller must learn "not found" for a genuinely missing id,
    // rather than be told "forbidden" about something that never existed.
    let entry = guestauth::guest_get_or_404!("inspections", id);
    let row: StoredInspection = serde_json::from_str(&entry.data).unwrap_or_default();
    guestauth::guest_deny_unless!(
        owns_or_admin("read", &principal, &row.inspector),
        principal,
        "inspection.read",
        id
    );
    Reply::json(200, one_json(&entry))
}

fn get_pdf(route: &Route, id: &str) -> Reply {
    use crate::bindings::pdf::codec::codec as pdf;

    let principal = guestauth::guest_authenticated!(route);
    let entry = guestauth::guest_get_or_404!("inspections", id);
    let row: StoredInspection = serde_json::from_str(&entry.data).unwrap_or_default();
    guestauth::guest_deny_unless!(
        owns_or_admin("read", &principal, &row.inspector),
        principal,
        "inspection.read",
        id
    );

    let line = |text: String, size: u32, bold: bool, gap_before: u32| pdf::Block {
        text,
        size,
        bold,
        gap_before,
    };
    let mut blocks = vec![
        line(format!("Site: {}", row.site_name), 12, false, 0),
        line(format!("Inspector: {}", row.inspector), 12, false, 0),
        line(format!("Date: {}", row.created), 12, false, 8),
    ];
    for item in &row.items {
        let verdict = if item.pass { "PASS" } else { "FAIL" };
        blocks.push(line(format!("{verdict} — {}", item.label), 11, true, 6));
        if !item.note.is_empty() {
            blocks.push(line(format!("  {}", item.note), 10, false, 0));
        }
    }
    let overall = if row.overall_pass { "PASS" } else { "FAIL" };
    blocks.push(line(format!("Overall: {overall}"), 13, true, 12));
    let doc = pdf::Document { title: "Site Inspection Report".to_string(), blocks };
    Reply::file(200, "application/pdf", pdf::render(&doc))
}
