// Generated by `wit-bindgen` 0.61.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     wasi:io@0.2.0
//     wasi:cli@0.2.0
//     wasi:clocks@0.2.0
//     wasi:random@0.2.0
//     price:history@0.1.0

package wasi_io_error

import (
	witRuntime "go.bytecodealliance.org/pkg/wit/runtime"
	"runtime"
	"unsafe"
)

//go:wasmimport wasi:io/error@0.2.0 [resource-drop]error
func resourceDropError(handle int32)

type Error struct {
	handle *witRuntime.Handle
}

func (self *Error) TakeHandle() int32 {
	return self.handle.Take()
}

func (self *Error) SetHandle(handle int32) {
	self.handle.Set(handle)
}

func (self *Error) Handle() int32 {
	return self.handle.Use()
}

func (self *Error) Drop() {
	handle := self.handle.TakeOrNil()
	if handle != 0 {
		resourceDropError(handle)
	}
}

func ErrorFromOwnHandle(handleValue int32) *Error {
	handle := witRuntime.MakeHandle(handleValue)
	value := &Error{handle}
	runtime.AddCleanup(value, func(_ int) {
		handleValue := handle.TakeOrNil()
		if handleValue != 0 {
			resourceDropError(handleValue)
		}
	}, 0)
	return value
}

func ErrorFromBorrowHandle(handleValue int32) *Error {
	handle := witRuntime.MakeHandle(handleValue)
	return &Error{handle}
}

//go:wasmimport wasi:io/error@0.2.0 [method]error.to-debug-string
func wasm_import_method_error_to_debug_string(arg0 int32, arg1 uintptr)

func (self *Error) ToDebugString() string {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (2 * 4), 4))
	wasm_import_method_error_to_debug_string((self).Handle(), returnArea)
	value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4)))
	result := value
	return result

}
