// Generated by `wit-bindgen` 0.61.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     wasi:io@0.2.0
//     wasi:cli@0.2.0
//     wasi:clocks@0.2.0
//     wasi:random@0.2.0
//     portfolio:value@0.1.0

package portfolio_value_valuation

import (
	witTypes "go.bytecodealliance.org/pkg/wit/types"
)

const (
	// Bought, or received in a swap.
	EventKindAcquired uint8 = 0
	// Sold, or given up in a swap.
	EventKindDisposed uint8 = 1
)

// What happened to an item, and when.
//
// A swap is two events, not one: what left is a disposal at the agreed value
// and what arrived is an acquisition at that same value, so a trade where you
// got the better end shows up as a gain.
type EventKind = uint8

// One thing that happened to one item.
type Event struct {
	// Opaque: whatever the caller uses to identify a thing.
	ItemId string
	Kind   EventKind
	// Copies. Zero is an error, not a no-op.
	Quantity uint32
	// Price per copy, in minor units of `currency`.
	UnitMinor int64
	// ISO-4217, compared exactly and never converted.
	Currency string
	// Unix seconds. Events are SORTED by this rather than trusted in order,
	// because backfilling an old purchase must not change the answer.
	At uint64
}

// The latest known price for an item at some instant.
type Quote struct {
	ItemId    string
	UnitMinor int64
	Currency  string
	// Unix seconds observed. Used for any instant at or after this one, until
	// a later quote replaces it.
	At uint64
}

// What a collection is worth, and how it got there.
type Valuation struct {
	// What the items still held cost.
	CostBasisMinor int64
	// What they are worth — quoted at market, UNQUOTED AT COST.
	MarketValueMinor int64
	// `market-value-minor - cost-basis-minor`. Held items only.
	UnrealisedMinor int64
	// Proceeds minus FIFO cost over every disposal up to this instant.
	RealisedMinor int64
	Currency      string
	// Copies still held that no quote covered. They are inside
	// `market-value-minor` at cost, and counted here so a caller can say so
	// rather than showing a total that pretends to be complete.
	Unquoted uint32
}

// One sample on the value chart.
type Point struct {
	At               uint64
	MarketValueMinor int64
	CostBasisMinor   int64
	RealisedMinor    int64
	Unquoted         uint32
}

const (
	// Two currencies in one portfolio. The rate on the day of a purchase eight
	// years ago is not knowable here, and inventing one puts a wrong number on
	// a chart that looks right. Carries expected and found.
	ValueErrorMixedCurrency uint8 = 0
	// A disposal of more copies than were held. The event log is wrong, and
	// guessing which is a bigger lie than refusing. Carries item, instant,
	// held, disposed.
	ValueErrorOversoldAt uint8 = 1
	// A zero-quantity event: always a bug upstream. Carries item and instant.
	ValueErrorZeroQuantity uint8 = 2
	// A step of zero does not terminate.
	ValueErrorZeroStep uint8 = 3
	// No events, so there is no currency to report a zero IN.
	ValueErrorEmpty uint8 = 4
)

// Why a valuation could not be produced. Every one of these is a silent wrong
// number if it is absorbed instead of refused.
type ValueError struct {
	tag   uint8
	value any
}

func (self ValueError) Tag() uint8 {
	return self.tag
}

func (self ValueError) MixedCurrency() witTypes.Tuple2[string, string] {
	if self.tag != ValueErrorMixedCurrency {
		panic("tag mismatch")
	}
	return self.value.(witTypes.Tuple2[string, string])
}
func (self ValueError) OversoldAt() witTypes.Tuple4[string, uint64, uint32, uint32] {
	if self.tag != ValueErrorOversoldAt {
		panic("tag mismatch")
	}
	return self.value.(witTypes.Tuple4[string, uint64, uint32, uint32])
}
func (self ValueError) ZeroQuantity() witTypes.Tuple2[string, uint64] {
	if self.tag != ValueErrorZeroQuantity {
		panic("tag mismatch")
	}
	return self.value.(witTypes.Tuple2[string, uint64])
}

func MakeValueErrorMixedCurrency(value witTypes.Tuple2[string, string]) ValueError {
	return ValueError{ValueErrorMixedCurrency, value}
}
func MakeValueErrorOversoldAt(value witTypes.Tuple4[string, uint64, uint32, uint32]) ValueError {
	return ValueError{ValueErrorOversoldAt, value}
}
func MakeValueErrorZeroQuantity(value witTypes.Tuple2[string, uint64]) ValueError {
	return ValueError{ValueErrorZeroQuantity, value}
}
func MakeValueErrorZeroStep() ValueError {
	return ValueError{ValueErrorZeroStep, nil}
}
func MakeValueErrorEmpty() ValueError {
	return ValueError{ValueErrorEmpty, nil}
}
