[package]
name = "ecommerce-fulfillment-domain"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen = { workspace = true }
guestio = { path = "../guestio" }
guestfmt = { path = "../guestfmt" }
serde_json = { workspace = true }
serde = { workspace = true, features = ["derive"] }
uuid = { version = "1.7.0", features = ["v4"] }
