package holon:budget;

world budget {
    import auth:identity/authorizer@0.1.0;
    import wasi:keyvalue/store@0.2.0-draft;

    export add-transaction: func(token: string, amount: f64, category: string, is-income: bool);
    export get-balance: func(token: string) -> f64;
    export get-category-budget: func(token: string, category: string) -> f64;
}
