// Generated by `wit-bindgen` 0.61.0. DO NOT EDIT!
#ifndef __BINDINGS_PORTFOLIO_VALUE_H
#define __BINDINGS_PORTFOLIO_VALUE_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

typedef struct portfolio_value_string_t {
  uint8_t*ptr;
  size_t len;
} portfolio_value_string_t;

// What happened to an item, and when.
// 
// A swap is two events, not one: what left is a disposal at the agreed value
// and what arrived is an acquisition at that same value, so a trade where you
// got the better end shows up as a gain.
typedef uint8_t exports_portfolio_value_valuation_event_kind_t;

// Bought, or received in a swap.
#define EXPORTS_PORTFOLIO_VALUE_VALUATION_EVENT_KIND_ACQUIRED 0
// Sold, or given up in a swap.
#define EXPORTS_PORTFOLIO_VALUE_VALUATION_EVENT_KIND_DISPOSED 1

// One thing that happened to one item.
typedef struct exports_portfolio_value_valuation_event_t {
  // Opaque: whatever the caller uses to identify a thing.
  portfolio_value_string_t   item_id;
  exports_portfolio_value_valuation_event_kind_t   kind;
  // Copies. Zero is an error, not a no-op.
  uint32_t   quantity;
  // Price per copy, in minor units of `currency`.
  int64_t   unit_minor;
  // ISO-4217, compared exactly and never converted.
  portfolio_value_string_t   currency;
  // Unix seconds. Events are SORTED by this rather than trusted in order,
  // because backfilling an old purchase must not change the answer.
  uint64_t   at;
} exports_portfolio_value_valuation_event_t;

// The latest known price for an item at some instant.
typedef struct exports_portfolio_value_valuation_quote_t {
  portfolio_value_string_t   item_id;
  int64_t   unit_minor;
  portfolio_value_string_t   currency;
  // Unix seconds observed. Used for any instant at or after this one, until
  // a later quote replaces it.
  uint64_t   at;
} exports_portfolio_value_valuation_quote_t;

// What a collection is worth, and how it got there.
typedef struct exports_portfolio_value_valuation_valuation_t {
  // What the items still held cost.
  int64_t   cost_basis_minor;
  // What they are worth — quoted at market, UNQUOTED AT COST.
  int64_t   market_value_minor;
  // `market-value-minor - cost-basis-minor`. Held items only.
  int64_t   unrealised_minor;
  // Proceeds minus FIFO cost over every disposal up to this instant.
  int64_t   realised_minor;
  portfolio_value_string_t   currency;
  // Copies still held that no quote covered. They are inside
  // `market-value-minor` at cost, and counted here so a caller can say so
  // rather than showing a total that pretends to be complete.
  uint32_t   unquoted;
} exports_portfolio_value_valuation_valuation_t;

// One sample on the value chart.
typedef struct exports_portfolio_value_valuation_point_t {
  uint64_t   at;
  int64_t   market_value_minor;
  int64_t   cost_basis_minor;
  int64_t   realised_minor;
  uint32_t   unquoted;
} exports_portfolio_value_valuation_point_t;

typedef struct {
  portfolio_value_string_t f0;
  portfolio_value_string_t f1;
} portfolio_value_tuple2_string_string_t;

typedef struct {
  portfolio_value_string_t f0;
  uint64_t f1;
  uint32_t f2;
  uint32_t f3;
} portfolio_value_tuple4_string_u64_u32_u32_t;

typedef struct {
  portfolio_value_string_t f0;
  uint64_t f1;
} portfolio_value_tuple2_string_u64_t;

// Why a valuation could not be produced. Every one of these is a silent wrong
// number if it is absorbed instead of refused.
typedef struct exports_portfolio_value_valuation_value_error_t {
  uint8_t tag;
  union {
    portfolio_value_tuple2_string_string_t     mixed_currency;
    portfolio_value_tuple4_string_u64_u32_u32_t     oversold_at;
    portfolio_value_tuple2_string_u64_t     zero_quantity;
  } val;
} exports_portfolio_value_valuation_value_error_t;

// Two currencies in one portfolio. The rate on the day of a purchase eight
// years ago is not knowable here, and inventing one puts a wrong number on
// a chart that looks right. Carries expected and found.
#define EXPORTS_PORTFOLIO_VALUE_VALUATION_VALUE_ERROR_MIXED_CURRENCY 0
// A disposal of more copies than were held. The event log is wrong, and
// guessing which is a bigger lie than refusing. Carries item, instant,
// held, disposed.
#define EXPORTS_PORTFOLIO_VALUE_VALUATION_VALUE_ERROR_OVERSOLD_AT 1
// A zero-quantity event: always a bug upstream. Carries item and instant.
#define EXPORTS_PORTFOLIO_VALUE_VALUATION_VALUE_ERROR_ZERO_QUANTITY 2
// A step of zero does not terminate.
#define EXPORTS_PORTFOLIO_VALUE_VALUATION_VALUE_ERROR_ZERO_STEP 3
// No events, so there is no currency to report a zero IN.
#define EXPORTS_PORTFOLIO_VALUE_VALUATION_VALUE_ERROR_EMPTY 4

typedef struct {
  exports_portfolio_value_valuation_event_t *ptr;
  size_t len;
} exports_portfolio_value_valuation_list_event_t;

typedef struct {
  exports_portfolio_value_valuation_quote_t *ptr;
  size_t len;
} exports_portfolio_value_valuation_list_quote_t;

typedef struct {
  bool is_err;
  union {
    exports_portfolio_value_valuation_valuation_t ok;
    exports_portfolio_value_valuation_value_error_t err;
  } val;
} exports_portfolio_value_valuation_result_valuation_value_error_t;

typedef struct {
  exports_portfolio_value_valuation_point_t *ptr;
  size_t len;
} exports_portfolio_value_valuation_list_point_t;

typedef struct {
  bool is_err;
  union {
    exports_portfolio_value_valuation_list_point_t ok;
    exports_portfolio_value_valuation_value_error_t err;
  } val;
} exports_portfolio_value_valuation_result_list_point_value_error_t;

// Exported Functions from `portfolio:value/valuation@0.1.0`
bool exports_portfolio_value_valuation_value_at(exports_portfolio_value_valuation_list_event_t *events, exports_portfolio_value_valuation_list_quote_t *quotes, uint64_t at, exports_portfolio_value_valuation_valuation_t *ret, exports_portfolio_value_valuation_value_error_t *err);
bool exports_portfolio_value_valuation_series(exports_portfolio_value_valuation_list_event_t *events, exports_portfolio_value_valuation_list_quote_t *quotes, uint64_t since, uint64_t until, uint64_t step, exports_portfolio_value_valuation_list_point_t *ret, exports_portfolio_value_valuation_value_error_t *err);

// Helper Functions

void exports_portfolio_value_valuation_event_free(exports_portfolio_value_valuation_event_t *ptr);

void exports_portfolio_value_valuation_quote_free(exports_portfolio_value_valuation_quote_t *ptr);

void exports_portfolio_value_valuation_valuation_free(exports_portfolio_value_valuation_valuation_t *ptr);

void portfolio_value_tuple2_string_string_free(portfolio_value_tuple2_string_string_t *ptr);

void portfolio_value_tuple4_string_u64_u32_u32_free(portfolio_value_tuple4_string_u64_u32_u32_t *ptr);

void portfolio_value_tuple2_string_u64_free(portfolio_value_tuple2_string_u64_t *ptr);

void exports_portfolio_value_valuation_value_error_free(exports_portfolio_value_valuation_value_error_t *ptr);

void exports_portfolio_value_valuation_list_event_free(exports_portfolio_value_valuation_list_event_t *ptr);

void exports_portfolio_value_valuation_list_quote_free(exports_portfolio_value_valuation_list_quote_t *ptr);

void exports_portfolio_value_valuation_result_valuation_value_error_free(exports_portfolio_value_valuation_result_valuation_value_error_t *ptr);

void exports_portfolio_value_valuation_list_point_free(exports_portfolio_value_valuation_list_point_t *ptr);

void exports_portfolio_value_valuation_result_list_point_value_error_free(exports_portfolio_value_valuation_result_list_point_value_error_t *ptr);

// Sets the string `ret` to reference the input string `s` without copying it
void portfolio_value_string_set(portfolio_value_string_t *ret, const char*s);

// Creates a copy of the input nul-terminated string `s` and
// stores it into the component model string `ret`.
void portfolio_value_string_dup(portfolio_value_string_t *ret, const char*s);

// Creates a copy of the input string `s` with length `len` and
// stores it into the component model string `ret`.
// The length is specified in code units (bytes for UTF-8, 16-bit values for UTF-16).
void portfolio_value_string_dup_n(portfolio_value_string_t *ret, const char*s, size_t len);

// Deallocates the string pointed to by `ret`, deallocating
// the memory behind the string.
void portfolio_value_string_free(portfolio_value_string_t *ret);

#ifdef __cplusplus
}
#endif
#endif
