// Generated by `wit-bindgen` 0.61.0. DO NOT EDIT!
#include "portfolio_value.h"
#include <stdlib.h>
#include <string.h>

// Exported Functions from `portfolio:value/valuation@0.1.0`

__attribute__((__weak__, __export_name__("cabi_post_portfolio:value/valuation@0.1.0#value-at")))
void __wasm_export_exports_portfolio_value_valuation_value_at_post_return(uint8_t * arg0) {
  switch ((int32_t) (int32_t) *((uint8_t*) (arg0 + 0))) {
    case 0: {
      if ((*((size_t*) (arg0 + (40+1*sizeof(void*))))) > 0) {
        free(*((uint8_t **) (arg0 + 40)));
      }
      break;
    }
    case 1: {
      switch ((int32_t) (int32_t) *((uint8_t*) (arg0 + 8))) {
        case 0: {
          if ((*((size_t*) (arg0 + (16+1*sizeof(void*))))) > 0) {
            free(*((uint8_t **) (arg0 + 16)));
          }
          if ((*((size_t*) (arg0 + (16+3*sizeof(void*))))) > 0) {
            free(*((uint8_t **) (arg0 + (16+2*sizeof(void*)))));
          }
          break;
        }
        case 1: {
          if ((*((size_t*) (arg0 + (16+1*sizeof(void*))))) > 0) {
            free(*((uint8_t **) (arg0 + 16)));
          }
          break;
        }
        case 2: {
          if ((*((size_t*) (arg0 + (16+1*sizeof(void*))))) > 0) {
            free(*((uint8_t **) (arg0 + 16)));
          }
          break;
        }
        case 3: {
          break;
        }
        case 4: {
          break;
        }
      }
      break;
    }
  }
}

__attribute__((__weak__, __export_name__("cabi_post_portfolio:value/valuation@0.1.0#series")))
void __wasm_export_exports_portfolio_value_valuation_series_post_return(uint8_t * arg0) {
  switch ((int32_t) (int32_t) *((uint8_t*) (arg0 + 0))) {
    case 0: {
      size_t len = *((size_t*) (arg0 + (8+1*sizeof(void*))));
      if (len > 0) {
        uint8_t *ptr = *((uint8_t **) (arg0 + 8));
        for (size_t i = 0; i < len; i++) {
          uint8_t *base = ptr + i * 40;
          (void) base;
        }
        free(ptr);
      }
      break;
    }
    case 1: {
      switch ((int32_t) (int32_t) *((uint8_t*) (arg0 + 8))) {
        case 0: {
          if ((*((size_t*) (arg0 + (16+1*sizeof(void*))))) > 0) {
            free(*((uint8_t **) (arg0 + 16)));
          }
          if ((*((size_t*) (arg0 + (16+3*sizeof(void*))))) > 0) {
            free(*((uint8_t **) (arg0 + (16+2*sizeof(void*)))));
          }
          break;
        }
        case 1: {
          if ((*((size_t*) (arg0 + (16+1*sizeof(void*))))) > 0) {
            free(*((uint8_t **) (arg0 + 16)));
          }
          break;
        }
        case 2: {
          if ((*((size_t*) (arg0 + (16+1*sizeof(void*))))) > 0) {
            free(*((uint8_t **) (arg0 + 16)));
          }
          break;
        }
        case 3: {
          break;
        }
        case 4: {
          break;
        }
      }
      break;
    }
  }
}

// Canonical ABI intrinsics

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  (void) old_size;
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}

__attribute__((__aligned__(8)))
static uint8_t RET_AREA[(48+2*sizeof(void*))];

// Helper Functions

void exports_portfolio_value_valuation_event_free(exports_portfolio_value_valuation_event_t *ptr) {
  portfolio_value_string_free(&ptr->item_id);
  portfolio_value_string_free(&ptr->currency);
}

void exports_portfolio_value_valuation_quote_free(exports_portfolio_value_valuation_quote_t *ptr) {
  portfolio_value_string_free(&ptr->item_id);
  portfolio_value_string_free(&ptr->currency);
}

void exports_portfolio_value_valuation_valuation_free(exports_portfolio_value_valuation_valuation_t *ptr) {
  portfolio_value_string_free(&ptr->currency);
}

void portfolio_value_tuple2_string_string_free(portfolio_value_tuple2_string_string_t *ptr) {
  portfolio_value_string_free(&ptr->f0);
  portfolio_value_string_free(&ptr->f1);
}

void portfolio_value_tuple4_string_u64_u32_u32_free(portfolio_value_tuple4_string_u64_u32_u32_t *ptr) {
  portfolio_value_string_free(&ptr->f0);
}

void portfolio_value_tuple2_string_u64_free(portfolio_value_tuple2_string_u64_t *ptr) {
  portfolio_value_string_free(&ptr->f0);
}

void exports_portfolio_value_valuation_value_error_free(exports_portfolio_value_valuation_value_error_t *ptr) {
  switch ((int32_t) ptr->tag) {
    case 0: {
      portfolio_value_tuple2_string_string_free(&ptr->val.mixed_currency);
      break;
    }
    case 1: {
      portfolio_value_tuple4_string_u64_u32_u32_free(&ptr->val.oversold_at);
      break;
    }
    case 2: {
      portfolio_value_tuple2_string_u64_free(&ptr->val.zero_quantity);
      break;
    }
  }
}

void exports_portfolio_value_valuation_list_event_free(exports_portfolio_value_valuation_list_event_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    exports_portfolio_value_valuation_event_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
      exports_portfolio_value_valuation_event_free(&list_ptr[i]);
    }
    free(list_ptr);
  }
}

void exports_portfolio_value_valuation_list_quote_free(exports_portfolio_value_valuation_list_quote_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    exports_portfolio_value_valuation_quote_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
      exports_portfolio_value_valuation_quote_free(&list_ptr[i]);
    }
    free(list_ptr);
  }
}

void exports_portfolio_value_valuation_result_valuation_value_error_free(exports_portfolio_value_valuation_result_valuation_value_error_t *ptr) {
  if (!ptr->is_err) {
    exports_portfolio_value_valuation_valuation_free(&ptr->val.ok);
  } else {
    exports_portfolio_value_valuation_value_error_free(&ptr->val.err);
  }
}

void exports_portfolio_value_valuation_list_point_free(exports_portfolio_value_valuation_list_point_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    exports_portfolio_value_valuation_point_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
    }
    free(list_ptr);
  }
}

void exports_portfolio_value_valuation_result_list_point_value_error_free(exports_portfolio_value_valuation_result_list_point_value_error_t *ptr) {
  if (!ptr->is_err) {
    exports_portfolio_value_valuation_list_point_free(&ptr->val.ok);
  } else {
    exports_portfolio_value_valuation_value_error_free(&ptr->val.err);
  }
}

void portfolio_value_string_set(portfolio_value_string_t *ret, const char*s) {
  ret->ptr = (uint8_t*) s;
  ret->len = strlen(s);
}

void portfolio_value_string_dup(portfolio_value_string_t *ret, const char*s) {
  ret->len = strlen(s);
  ret->ptr = (uint8_t*) cabi_realloc(NULL, 0, 1, ret->len * 1);
  memcpy(ret->ptr, s, ret->len * 1);
}

void portfolio_value_string_dup_n(portfolio_value_string_t *ret, const char*s, size_t len) {
  ret->len = len;
  ret->ptr = (uint8_t*) cabi_realloc(NULL, 0, 1, ret->len * 1);
  memcpy(ret->ptr, s, ret->len * 1);
}

void portfolio_value_string_free(portfolio_value_string_t *ret) {
  if (ret->len > 0) {
    free(ret->ptr);
  }
  ret->ptr = NULL;
  ret->len = 0;
}

// Component Adapters

__attribute__((__export_name__("portfolio:value/valuation@0.1.0#value-at")))
uint8_t * __wasm_export_exports_portfolio_value_valuation_value_at(uint8_t * arg, size_t arg0, uint8_t * arg1, size_t arg2, int64_t arg3) {
  exports_portfolio_value_valuation_list_event_t arg4 = (exports_portfolio_value_valuation_list_event_t) { (exports_portfolio_value_valuation_event_t*)(arg), (arg0) };
  exports_portfolio_value_valuation_list_quote_t arg5 = (exports_portfolio_value_valuation_list_quote_t) { (exports_portfolio_value_valuation_quote_t*)(arg1), (arg2) };
  exports_portfolio_value_valuation_result_valuation_value_error_t ret;
  exports_portfolio_value_valuation_valuation_t ok;
  exports_portfolio_value_valuation_value_error_t err;
  ret.is_err = !exports_portfolio_value_valuation_value_at(&arg4, &arg5, (uint64_t) (arg3), &ok, &err);
  if (ret.is_err) {
    ret.val.err = err;
  }
  if (!ret.is_err) {
    ret.val.ok = ok;
  }
  uint8_t *ptr = (uint8_t *) &RET_AREA;
  if ((ret).is_err) {
    const exports_portfolio_value_valuation_value_error_t *payload6 = &(ret).val.err;*((int8_t*)(ptr + 0)) = 1;
    switch ((int32_t) (*payload6).tag) {
      case 0: {
        const portfolio_value_tuple2_string_string_t *payload7 = &(*payload6).val.mixed_currency;
        *((int8_t*)(ptr + 8)) = 0;
        *((size_t*)(ptr + (16+1*sizeof(void*)))) = ((*payload7).f0).len;
        *((uint8_t **)(ptr + 16)) = (uint8_t *) ((*payload7).f0).ptr;
        *((size_t*)(ptr + (16+3*sizeof(void*)))) = ((*payload7).f1).len;
        *((uint8_t **)(ptr + (16+2*sizeof(void*)))) = (uint8_t *) ((*payload7).f1).ptr;
        break;
      }
      case 1: {
        const portfolio_value_tuple4_string_u64_u32_u32_t *payload8 = &(*payload6).val.oversold_at;
        *((int8_t*)(ptr + 8)) = 1;
        *((size_t*)(ptr + (16+1*sizeof(void*)))) = ((*payload8).f0).len;
        *((uint8_t **)(ptr + 16)) = (uint8_t *) ((*payload8).f0).ptr;
        *((int64_t*)(ptr + (16+2*sizeof(void*)))) = (int64_t) ((*payload8).f1);
        *((int32_t*)(ptr + (24+2*sizeof(void*)))) = (int32_t) ((*payload8).f2);
        *((int32_t*)(ptr + (28+2*sizeof(void*)))) = (int32_t) ((*payload8).f3);
        break;
      }
      case 2: {
        const portfolio_value_tuple2_string_u64_t *payload9 = &(*payload6).val.zero_quantity;
        *((int8_t*)(ptr + 8)) = 2;
        *((size_t*)(ptr + (16+1*sizeof(void*)))) = ((*payload9).f0).len;
        *((uint8_t **)(ptr + 16)) = (uint8_t *) ((*payload9).f0).ptr;
        *((int64_t*)(ptr + (16+2*sizeof(void*)))) = (int64_t) ((*payload9).f1);
        break;
      }
      case 3: {
        *((int8_t*)(ptr + 8)) = 3;
        break;
      }
      case 4: {
        *((int8_t*)(ptr + 8)) = 4;
        break;
      }
    }
  } else {
    const exports_portfolio_value_valuation_valuation_t *payload = &(ret).val.ok;*((int8_t*)(ptr + 0)) = 0;
    *((int64_t*)(ptr + 8)) = (*payload).cost_basis_minor;
    *((int64_t*)(ptr + 16)) = (*payload).market_value_minor;
    *((int64_t*)(ptr + 24)) = (*payload).unrealised_minor;
    *((int64_t*)(ptr + 32)) = (*payload).realised_minor;
    *((size_t*)(ptr + (40+1*sizeof(void*)))) = ((*payload).currency).len;
    *((uint8_t **)(ptr + 40)) = (uint8_t *) ((*payload).currency).ptr;
    *((int32_t*)(ptr + (40+2*sizeof(void*)))) = (int32_t) ((*payload).unquoted);
  }
  return ptr;
}

__attribute__((__export_name__("portfolio:value/valuation@0.1.0#series")))
uint8_t * __wasm_export_exports_portfolio_value_valuation_series(uint8_t * arg, size_t arg0, uint8_t * arg1, size_t arg2, int64_t arg3, int64_t arg4, int64_t arg5) {
  exports_portfolio_value_valuation_list_event_t arg6 = (exports_portfolio_value_valuation_list_event_t) { (exports_portfolio_value_valuation_event_t*)(arg), (arg0) };
  exports_portfolio_value_valuation_list_quote_t arg7 = (exports_portfolio_value_valuation_list_quote_t) { (exports_portfolio_value_valuation_quote_t*)(arg1), (arg2) };
  exports_portfolio_value_valuation_result_list_point_value_error_t ret;
  exports_portfolio_value_valuation_list_point_t ok;
  exports_portfolio_value_valuation_value_error_t err;
  ret.is_err = !exports_portfolio_value_valuation_series(&arg6, &arg7, (uint64_t) (arg3), (uint64_t) (arg4), (uint64_t) (arg5), &ok, &err);
  if (ret.is_err) {
    ret.val.err = err;
  }
  if (!ret.is_err) {
    ret.val.ok = ok;
  }
  uint8_t *ptr = (uint8_t *) &RET_AREA;
  if ((ret).is_err) {
    const exports_portfolio_value_valuation_value_error_t *payload8 = &(ret).val.err;*((int8_t*)(ptr + 0)) = 1;
    switch ((int32_t) (*payload8).tag) {
      case 0: {
        const portfolio_value_tuple2_string_string_t *payload9 = &(*payload8).val.mixed_currency;
        *((int8_t*)(ptr + 8)) = 0;
        *((size_t*)(ptr + (16+1*sizeof(void*)))) = ((*payload9).f0).len;
        *((uint8_t **)(ptr + 16)) = (uint8_t *) ((*payload9).f0).ptr;
        *((size_t*)(ptr + (16+3*sizeof(void*)))) = ((*payload9).f1).len;
        *((uint8_t **)(ptr + (16+2*sizeof(void*)))) = (uint8_t *) ((*payload9).f1).ptr;
        break;
      }
      case 1: {
        const portfolio_value_tuple4_string_u64_u32_u32_t *payload10 = &(*payload8).val.oversold_at;
        *((int8_t*)(ptr + 8)) = 1;
        *((size_t*)(ptr + (16+1*sizeof(void*)))) = ((*payload10).f0).len;
        *((uint8_t **)(ptr + 16)) = (uint8_t *) ((*payload10).f0).ptr;
        *((int64_t*)(ptr + (16+2*sizeof(void*)))) = (int64_t) ((*payload10).f1);
        *((int32_t*)(ptr + (24+2*sizeof(void*)))) = (int32_t) ((*payload10).f2);
        *((int32_t*)(ptr + (28+2*sizeof(void*)))) = (int32_t) ((*payload10).f3);
        break;
      }
      case 2: {
        const portfolio_value_tuple2_string_u64_t *payload11 = &(*payload8).val.zero_quantity;
        *((int8_t*)(ptr + 8)) = 2;
        *((size_t*)(ptr + (16+1*sizeof(void*)))) = ((*payload11).f0).len;
        *((uint8_t **)(ptr + 16)) = (uint8_t *) ((*payload11).f0).ptr;
        *((int64_t*)(ptr + (16+2*sizeof(void*)))) = (int64_t) ((*payload11).f1);
        break;
      }
      case 3: {
        *((int8_t*)(ptr + 8)) = 3;
        break;
      }
      case 4: {
        *((int8_t*)(ptr + 8)) = 4;
        break;
      }
    }
  } else {
    const exports_portfolio_value_valuation_list_point_t *payload = &(ret).val.ok;*((int8_t*)(ptr + 0)) = 0;
    *((size_t*)(ptr + (8+1*sizeof(void*)))) = (*payload).len;
    *((uint8_t **)(ptr + 8)) = (uint8_t *) (*payload).ptr;
  }
  return ptr;
}

// Ensure that the *_component_type.o object is linked in

extern void __component_type_object_force_link_portfolio_value(void);
__attribute__((used))
void __component_type_object_force_link_portfolio_value_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_portfolio_value();
}
