// App factory for the jco-embed example. The auth-guard component runs
// IN-PROCESS (jco-transpiled into ./gen), so this Fastify app calls its exports
// directly — no network, no wasmCloud. Importable by tests via app.inject.

import Fastify, { type FastifyInstance, type FastifyReply } from "fastify";
// Generated by `jco transpile` (run `npm run transpile` first).
import { accounts, authorizer, rbac, session } from "../gen/auth_guard.js";

interface Principal {
  subject: string;
  tenant: string;
  roles: string[];
  scopes: string[];
}
interface AuthErr {
  tag: string;
  val?: unknown;
}

// Map a thrown auth-error variant to an HTTP status + code.
function statusFor(e: AuthErr): [number, string] {
  switch (e.tag) {
    case "invalid-credentials": return [401, "invalid_credentials"];
    case "already-exists": return [409, "already_exists"];
    case "rate-limited": return [429, "rate_limited"];
    case "insufficient-scope": return [403, "insufficient_scope"];
    case "expired": return [401, "expired"];
    case "invalid-token": return [401, "invalid_token"];
    case "unknown-tenant": return [403, "unknown_tenant"];
    case "malformed": return [400, "malformed"];
    case "backend-unavailable": return [503, "backend_unavailable"];
    default: return [500, "internal"];
  }
}

function bearer(auth?: string): string | undefined {
  return auth?.startsWith("Bearer ") ? auth.slice(7).trim() : undefined;
}

export function buildApp(opts: { logger?: boolean } = {}): FastifyInstance {
  const app = Fastify({ logger: opts.logger ?? false });

  // WIT u64 (expires-at / expires-in) arrives as JS BigInt, which
  // JSON.stringify can't serialize. Coerce BigInt -> Number on the way out.
  app.setReplySerializer((payload) =>
    JSON.stringify(payload, (_k, v) => (typeof v === "bigint" ? Number(v) : v)),
  );

  // Wrap a direct component call: translate thrown auth-errors into HTTP.
  const guarded = <T>(reply: FastifyReply, fn: () => T): T | undefined => {
    try {
      return fn();
    } catch (e) {
      const err = (
        e && typeof e === "object" && "payload" in e
          ? (e as { payload: unknown }).payload
          : e
      ) as AuthErr;
      if (!err || typeof err.tag !== "string") {
        app.log.error(e, "non-auth throw from component");
        reply.code(500).send({ error: "internal" });
        return undefined;
      }
      const [code, msg] = statusFor(err);
      reply.code(code).send({ error: msg });
      return undefined;
    }
  };

  app.post("/auth/register", async (request, reply) => {
    const { email, password, tenant } = request.body as Record<string, string>;
    const p = guarded(reply, () => accounts.register(email, password, tenant ?? "") as Principal);
    if (p) reply.code(201).send(p);
  });

  app.post("/auth/login", async (request, reply) => {
    const { email, password, tenant } = request.body as Record<string, string>;
    return guarded(reply, () => accounts.login(email, password, tenant ?? ""));
  });

  app.get("/auth/me", async (request, reply) => {
    const token = bearer(request.headers.authorization);
    if (!token) return reply.code(401).send({ error: "missing_bearer_token" });
    return guarded(reply, () => authorizer.introspect(token));
  });

  app.post("/auth/logout", async (request, reply) => {
    const token = bearer(request.headers.authorization);
    if (!token) return reply.code(401).send({ error: "missing_bearer_token" });
    guarded(reply, () => session.revoke(token));
    if (!reply.sent) reply.code(204).send();
  });

  // Exchange a refresh token for a fresh token pair (rotates; reuse of a
  // rotated token trips breach detection and revokes the session family).
  app.post("/auth/refresh", async (request, reply) => {
    const { refresh_token } = request.body as { refresh_token?: string };
    if (!refresh_token) return reply.code(400).send({ error: "missing_refresh_token" });
    return guarded(reply, () => session.refresh(refresh_token));
  });

  // Guarded business route — RBAC check happens inside the component.
  app.get("/orders", async (request, reply) => {
    const token = bearer(request.headers.authorization);
    if (!token) return reply.code(401).send({ error: "missing_bearer_token" });
    const principal = guarded(
      reply,
      () => authorizer.authorize(token, { target: "orders", action: "read" }) as Principal,
    );
    if (principal) return { orders: [{ id: 1, item: "widget" }], viewer: principal.subject };
  });

  // ---- admin (RBAC seeding) — unauthenticated in this example ----
  app.post("/admin/role-permissions", async (request, reply) => {
    const { tenant, role, permissions } = request.body as {
      tenant: string;
      role: string;
      permissions: { target: string; action: string }[];
    };
    guarded(reply, () => rbac.setRolePermissions(tenant, role, permissions));
    if (!reply.sent) reply.code(204).send();
  });

  app.post("/admin/assign-role", async (request, reply) => {
    const { tenant, subject, role } = request.body as {
      tenant: string;
      subject: string;
      role: string;
    };
    guarded(reply, () => rbac.assignRole(tenant, subject, role));
    if (!reply.sent) reply.code(204).send();
  });

  return app;
}
