//! The same graph, written three ways.
//!
//! These are not three formats for one idea — they are three different deployment
//! models, and the comments each emitter writes into its output say where they
//! diverge:
//!
//! * `plug_script` — imperative `wac plug`, one invocation per socket, in build
//!   order. Each socket gets its OWN instance of every plug.
//! * `wac_file` — declarative `wac compose`. A capability instantiated once is
//!   SHARED by every consumer wired to it. This is the only one of the two static
//!   forms that can express a diamond as a diamond.
//! * `workload` — a wasmCloud v2 `WorkloadDeployment`. Nothing is fused: the
//!   runtime links same-workload components in-process, so composable edges leave
//!   no trace in the manifest and only host capabilities appear.
//!
//! YAML is written by hand rather than through a serializer: every value here is
//! an identifier, a small integer, or a registry path, and a fixed shape emitted
//! by `format!` is less machinery than a serde dependency. The shape is pinned by
//! `emits_a_workload_manifest` against the fields `examples/*/k8s/*.yaml` use.

use std::collections::{BTreeMap, BTreeSet};

use crate::bindings::exports::wit::reflect::composer::{CompositionPlan, Edge, Node, WorkloadMeta};

/// cargo names artifacts with underscores; canvas ids carry hyphens.
fn artifact_stem(id: &str) -> String {
    id.replace('-', "_")
}

/// A wac-safe identifier for a `let` binding. wac identifiers are kebab-case like
/// WIT's: an underscore is a parse error, not a style preference.
fn ident(id: &str) -> String {
    let s: String = id.chars().map(|c| if c.is_ascii_alphanumeric() { c } else { '-' }).collect();
    let s = s.trim_matches('-').to_string();
    if s.is_empty() || s.starts_with(|c: char| c.is_ascii_digit()) {
        format!("c-{s}")
    } else {
        s
    }
}

// ---- imperative: wac plug ---------------------------------------------------

pub(crate) fn plug_script(plan: &CompositionPlan, out_dir: &str) -> String {
    let mut s = String::new();
    s.push_str("#!/usr/bin/env bash\n");
    s.push_str("# Generated by wit:reflect — this graph as `wac plug`, in build order.\n");
    s.push_str("#\n");
    s.push_str("# Note: `wac plug` gives every socket its OWN instance of each plug. If two\n");
    s.push_str("# components here plug in the same capability, the result contains it twice,\n");
    s.push_str("# with separate state. Use the .wac form if they must share one instance.\n");
    s.push_str("set -euo pipefail\n\n");
    s.push_str("REL=${REL:-components/target/wasm32-wasip2/release}\n");
    s.push_str(&format!("OUT=${{OUT:-{out_dir}}}\n"));
    s.push_str("mkdir -p \"$OUT\"\n\n");

    if plan.cyclic {
        s.push_str("# REFUSED: this graph has a cycle, so no build order exists.\n");
        for p in plan.problems.iter().filter(|p| p.kind == "cycle") {
            s.push_str(&format!("#   {}\n", p.detail));
        }
        return s;
    }

    // A plug that is itself a socket earlier in the order is consumed as the
    // composed intermediate, not as its raw artifact.
    let built: BTreeSet<&str> = plan.steps.iter().map(|st| st.socket.as_str()).collect();
    let path_of = |id: &str| -> String {
        if built.contains(id) {
            format!("\"$OUT/{}\"", format!("{}.composed.wasm", artifact_stem(id)))
        } else {
            format!("\"$REL/{}.wasm\"", artifact_stem(id))
        }
    };

    for step in &plan.steps {
        let output = format!("$OUT/{}.composed.wasm", artifact_stem(&step.socket));
        if !step.also_satisfies.is_empty() {
            s.push_str(&format!(
                "# also satisfies (wac matches every common interface, not just the ones you drew):\n#   {}\n",
                step.also_satisfies.join("\n#   ")
            ));
        }
        s.push_str(&format!("wac plug \"$REL/{}.wasm\" \\\n", artifact_stem(&step.socket)));
        for plug in &step.plugs {
            s.push_str(&format!("  --plug {} \\\n", path_of(plug)));
        }
        s.push_str(&format!("  -o \"{output}\"\n"));
        s.push_str(&format!("wasm-tools validate \"{output}\"\n\n"));
    }

    if !plan.unsatisfied.is_empty() {
        s.push_str("# Still imported by the result (no component on the canvas exports these):\n");
        for gap in &plan.unsatisfied {
            s.push_str(&format!("#   {} needs {}\n", gap.node, gap.iface.raw));
        }
        s.push('\n');
    }
    if !plan.host_needs.is_empty() {
        s.push_str("# Host capabilities the finished artifact needs at run time — a host\n");
        s.push_str("# provides these; no amount of composing removes them:\n");
        for h in &plan.host_needs {
            s.push_str(&format!("#   {}\n", h.raw));
        }
    }
    s
}

// ---- declarative: a .wac file ----------------------------------------------

/// The wac package name to instantiate a node as. A capability's identity is its
/// exported interface (`records:store/store@0.1.0` -> `records:store`); an app
/// that exports only `wasi:http` has no identity of its own in the binary, so it
/// gets `<id>:component`, matching how `components/login-app/compose.wac` names
/// its consumer.
fn wac_package(node: &Node) -> String {
    for e in &node.surface.exports {
        if e.namespace != "wasi" && !e.namespace.is_empty() {
            return format!("{}:{}", e.namespace, e.pkg);
        }
    }
    format!("{}:component", ident(&node.id))
}

pub(crate) fn wac_file(
    nodes: &[Node],
    edges: &[Edge],
    plan: &CompositionPlan,
    package_name: &str,
) -> String {
    let by_id: BTreeMap<&str, &Node> = nodes.iter().map(|n| (n.id.as_str(), n)).collect();
    let mut s = String::new();
    s.push_str("// Generated by wit:reflect — this graph as a `wac compose` source file.\n");
    s.push_str("//\n");
    s.push_str("// Unlike the `wac plug` script, each `let` below is ONE instance: a capability\n");
    s.push_str("// wired to two consumers is shared by them, state and all. That is the whole\n");
    s.push_str("// reason to prefer this form for anything shaped like a diamond.\n//\n");
    s.push_str("// Build it with (paths are yours to adjust):\n");
    s.push_str("//   wac compose composition.wac \\\n");
    for node in nodes {
        s.push_str(&format!(
            "//     --dep {}={} \\\n",
            wac_package(node),
            format!("components/target/wasm32-wasip2/release/{}.wasm", artifact_stem(&node.id))
        ));
    }
    s.push_str("//     -o composed.wasm\n\n");
    s.push_str(&format!("package {package_name};\n\n"));

    if plan.cyclic {
        s.push_str("// REFUSED: this graph has a cycle. A composition is a DAG; deploy it as a\n");
        s.push_str("// wasmCloud workload instead, where the runtime links at invoke time.\n");
        return s;
    }

    // Emit deepest-first so every referenced binding already exists.
    let depth: BTreeMap<&str, u32> = plan.depth.iter().map(|(id, d)| (id.as_str(), *d)).collect();
    let mut ordered: Vec<&Node> = nodes.iter().collect();
    ordered.sort_by_key(|n| (depth.get(n.id.as_str()).copied().unwrap_or(0), n.id.clone()));

    // socket -> (iface, plug id)
    let mut wiring: BTreeMap<&str, Vec<(&str, &str)>> = BTreeMap::new();
    for e in edges {
        if by_id.contains_key(e.plug.as_str()) && by_id.contains_key(e.socket.as_str()) {
            wiring.entry(e.socket.as_str()).or_default().push((e.iface.as_str(), e.plug.as_str()));
        }
    }

    for node in &ordered {
        let var = ident(&node.id);
        let pkg = wac_package(node);
        match wiring.get(node.id.as_str()) {
            None => {
                s.push_str(&format!("let {var} = new {pkg} {{ ... }};\n"));
            }
            Some(args) => {
                s.push_str(&format!("let {var} = new {pkg} {{\n"));
                for (iface, plug) in args {
                    // Bracket indexing, not dot access: interface names carry `:`
                    // `/` and `@`, none of which are identifier characters.
                    s.push_str(&format!("  \"{iface}\": {}[\"{iface}\"],\n", ident(plug)));
                }
                // `...` fills the remaining imports from the enclosing scope, so
                // host capabilities pass straight through to the final component.
                s.push_str("  ...\n};\n");
            }
        }
    }
    s.push('\n');
    for root in &plan.roots {
        s.push_str(&format!("export {}...;\n", ident(root)));
    }
    s
}

// ---- wasmCloud v2: a WorkloadDeployment ------------------------------------

pub(crate) fn workload(nodes: &[Node], plan: &CompositionPlan, meta: &WorkloadMeta) -> String {
    let name = if meta.name.is_empty() { "app" } else { meta.name.as_str() };
    let ns = if meta.namespace.is_empty() { name } else { meta.namespace.as_str() };
    let tag = if meta.tag.is_empty() { "0.1.0" } else { meta.tag.as_str() };
    let registry = if meta.registry.is_empty() {
        format!("registry.{ns}.svc.cluster.local:5000")
    } else {
        meta.registry.clone()
    };
    let replicas = meta.replicas.max(1);
    let pool = meta.pool_size.max(1);
    let max_inv = meta.max_invocations.max(1);
    let http_host = if meta.http_host.is_empty() {
        format!("{name}.{ns}.svc.cluster.local")
    } else {
        meta.http_host.clone()
    };
    let serves_http =
        nodes.iter().any(|n| n.surface.exports.iter().any(|e| e.name == "incoming-handler"));

    let mut s = String::new();
    s.push_str("# Generated by wit:reflect — this graph as a wasmCloud v2 workload.\n");
    s.push_str("#\n");
    s.push_str("# The v2 operator is NOT the link-trait model. Components listed in one\n");
    s.push_str("# WorkloadDeployment are linked IN-PROCESS by the runtime, so every edge you\n");
    s.push_str("# drew on the canvas is absent from this file by design — there is nothing to\n");
    s.push_str("# declare. What remains are host capabilities, as `hostInterfaces`.\n");
    s.push_str("#\n");
    s.push_str("# One entry per interface, deliberately: an entry binds to a component only if\n");
    s.push_str("# that component's world covers EVERY interface listed, so a merged\n");
    s.push_str("# [store, atomics] entry silently skips components importing only one.\n");
    if !plan.unsatisfied.is_empty() {
        s.push_str(
            "#\n# Unsatisfied on the canvas — fine here IF the exporter is a component in\n",
        );
        s.push_str(
            "# this same workload (the runtime wires it); otherwise it will fail to start:\n",
        );
        for gap in &plan.unsatisfied {
            s.push_str(&format!("#   {} needs {}\n", gap.node, gap.iface.raw));
        }
    }
    if plan.cyclic {
        s.push_str(
            "#\n# This graph is cyclic, which a static composition cannot express — but the\n",
        );
        s.push_str("# runtime links at invoke time, so here it is legal.\n");
    }

    s.push_str("apiVersion: runtime.wasmcloud.dev/v1alpha1\n");
    s.push_str("kind: WorkloadDeployment\n");
    s.push_str("metadata:\n");
    s.push_str(&format!("  name: {name}\n"));
    s.push_str(&format!("  namespace: {ns}\n"));
    s.push_str("spec:\n");
    s.push_str(&format!("  replicas: {replicas}\n"));
    s.push_str("  template:\n");
    s.push_str("    spec:\n");
    if serves_http {
        s.push_str("      kubernetes:\n        service:\n");
        s.push_str(&format!("          name: {name}\n"));
    }

    // hostInterfaces: one entry per (namespace, package, interface).
    let mut entries: BTreeSet<(String, String, String)> = BTreeSet::new();
    for h in &plan.host_needs {
        if h.namespace.is_empty() || h.pkg.is_empty() || h.name.is_empty() {
            continue;
        }
        entries.insert((h.namespace.clone(), h.pkg.clone(), h.name.clone()));
    }
    if serves_http {
        entries.insert(("wasi".into(), "http".into(), "incoming-handler".into()));
    }
    if !entries.is_empty() {
        s.push_str("      hostInterfaces:\n");
        for (namespace, package, iface) in &entries {
            s.push_str(&format!("        - namespace: {namespace}\n"));
            s.push_str(&format!("          package: {package}\n"));
            s.push_str(&format!("          interfaces: [{iface}]\n"));
            if namespace == "wasi" && package == "http" && iface == "incoming-handler" {
                s.push_str("          config:\n");
                s.push_str(&format!("            host: {http_host}\n"));
            }
        }
    }

    s.push_str("      components:\n");
    for node in nodes {
        s.push_str(&format!("        - name: {}\n", node.id));
        s.push_str(&format!("          image: {registry}/{}:{tag}\n", node.id));
        s.push_str(&format!("          poolSize: {pool}\n"));
        s.push_str(&format!("          maxInvocations: {max_inv}\n"));
    }

    if serves_http {
        s.push_str("---\n");
        s.push_str("# Selector-less on purpose: the operator's route controller maintains the\n");
        s.push_str("# endpoints for this Service.\n");
        s.push_str("apiVersion: v1\nkind: Service\n");
        s.push_str("metadata:\n");
        s.push_str(&format!("  name: {name}\n"));
        s.push_str(&format!("  namespace: {ns}\n"));
        s.push_str("spec:\n  ports:\n");
        s.push_str("    - name: http\n      port: 80\n      targetPort: 9191\n");
    }
    s
}
