// Generated by `wit-bindgen` 0.61.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     wasi:io@0.2.0
//     wasi:cli@0.2.0
//     wasi:clocks@0.2.0
//     wasi:random@0.2.0
//     portfolio:value@0.1.0

package main

import (
	witRuntime "go.bytecodealliance.org/pkg/wit/runtime"
	witTypes "go.bytecodealliance.org/pkg/wit/types"
	"runtime"
	"unsafe"
	"wit_component/export_portfolio_value_valuation"
	"wit_component/portfolio_value_valuation"
)

var staticPinner = runtime.Pinner{}
var exportReturnArea = uintptr(witRuntime.Allocate(&staticPinner, (48 + 2*4), 8))
var syncExportPinner = runtime.Pinner{}

//go:wasmexport portfolio:value/valuation@0.1.0#value-at
func wasm_export_portfolio_value_valuation_value_at(arg0 uintptr, arg1 uint32, arg2 uintptr, arg3 uint32, arg4 int64) uintptr {

	pinner := &syncExportPinner
	result := make([]portfolio_value_valuation.Event, 0, arg1)
	for index := 0; index < int(arg1); index++ {
		base := unsafe.Add(unsafe.Pointer(arg0), index*(24+4*4))
		value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)))
		value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (16 + 2*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (16 + 3*4))))

		result = append(result, portfolio_value_valuation.Event{ItemId: value, Kind: uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (2 * 4))))), Quantity: uint32(*(*int32)(unsafe.Add(unsafe.Pointer(base), (4 + 2*4)))), UnitMinor: *(*int64)(unsafe.Add(unsafe.Pointer(base), (8 + 2*4))), Currency: value0, At: uint64(*(*int64)(unsafe.Add(unsafe.Pointer(base), (16 + 4*4))))})
	}

	result3 := make([]portfolio_value_valuation.Quote, 0, arg3)
	for index := 0; index < int(arg3); index++ {
		base := unsafe.Add(unsafe.Pointer(arg2), index*(16+4*4))
		value1 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)))
		value2 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 2*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 3*4))))

		result3 = append(result3, portfolio_value_valuation.Quote{ItemId: value1, UnitMinor: *(*int64)(unsafe.Add(unsafe.Pointer(base), (2 * 4))), Currency: value2, At: uint64(*(*int64)(unsafe.Add(unsafe.Pointer(base), (8 + 4*4))))})
	}

	witRuntime.Unpin()
	result4 := export_portfolio_value_valuation.ValueAt(result, result3, uint64(arg4))

	switch result4.Tag() {
	case witTypes.ResultOk:
		payload := result4.Ok()
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(0))
		*(*int64)(unsafe.Add(unsafe.Pointer(exportReturnArea), 8)) = (payload).CostBasisMinor
		*(*int64)(unsafe.Add(unsafe.Pointer(exportReturnArea), 16)) = (payload).MarketValueMinor
		*(*int64)(unsafe.Add(unsafe.Pointer(exportReturnArea), 24)) = (payload).UnrealisedMinor
		*(*int64)(unsafe.Add(unsafe.Pointer(exportReturnArea), 32)) = (payload).RealisedMinor
		utf8 := unsafe.Pointer(unsafe.StringData((payload).Currency))
		pinner.Pin(utf8)
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (40 + 1*4))) = uint32(uint32(len((payload).Currency)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 40)) = uint32(uintptr(uintptr(utf8)))
		*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (40 + 2*4))) = int32((payload).Unquoted)

	case witTypes.ResultErr:
		payload := result4.Err()
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(1))

		switch payload.Tag() {
		case portfolio_value_valuation.ValueErrorMixedCurrency:
			payload := payload.MixedCurrency()
			*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 8)) = int8(int32(0))
			utf85 := unsafe.Pointer(unsafe.StringData((payload).F0))
			pinner.Pin(utf85)
			*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (16 + 1*4))) = uint32(uint32(len((payload).F0)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 16)) = uint32(uintptr(uintptr(utf85)))
			utf86 := unsafe.Pointer(unsafe.StringData((payload).F1))
			pinner.Pin(utf86)
			*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (16 + 3*4))) = uint32(uint32(len((payload).F1)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (16 + 2*4))) = uint32(uintptr(uintptr(utf86)))

		case portfolio_value_valuation.ValueErrorOversoldAt:
			payload := payload.OversoldAt()
			*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 8)) = int8(int32(1))
			utf87 := unsafe.Pointer(unsafe.StringData((payload).F0))
			pinner.Pin(utf87)
			*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (16 + 1*4))) = uint32(uint32(len((payload).F0)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 16)) = uint32(uintptr(uintptr(utf87)))
			*(*int64)(unsafe.Add(unsafe.Pointer(exportReturnArea), (16 + 2*4))) = int64((payload).F1)
			*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (24 + 2*4))) = int32((payload).F2)
			*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (28 + 2*4))) = int32((payload).F3)

		case portfolio_value_valuation.ValueErrorZeroQuantity:
			payload := payload.ZeroQuantity()
			*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 8)) = int8(int32(2))
			utf88 := unsafe.Pointer(unsafe.StringData((payload).F0))
			pinner.Pin(utf88)
			*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (16 + 1*4))) = uint32(uint32(len((payload).F0)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 16)) = uint32(uintptr(uintptr(utf88)))
			*(*int64)(unsafe.Add(unsafe.Pointer(exportReturnArea), (16 + 2*4))) = int64((payload).F1)

		case portfolio_value_valuation.ValueErrorZeroStep:

			*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 8)) = int8(int32(3))

		case portfolio_value_valuation.ValueErrorEmpty:

			*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 8)) = int8(int32(4))

		default:
			panic("unreachable")
		}

	default:
		panic("unreachable")
	}
	return exportReturnArea

}

//go:wasmexport cabi_post_portfolio:value/valuation@0.1.0#value-at
func wasm_export_post_return_portfolio_value_valuation_value_at(result uintptr) {
	syncExportPinner.Unpin()
}

//go:wasmexport portfolio:value/valuation@0.1.0#series
func wasm_export_portfolio_value_valuation_series(arg0 uintptr, arg1 uint32, arg2 uintptr, arg3 uint32, arg4 int64, arg5 int64, arg6 int64) uintptr {

	pinner := &syncExportPinner
	result := make([]portfolio_value_valuation.Event, 0, arg1)
	for index := 0; index < int(arg1); index++ {
		base := unsafe.Add(unsafe.Pointer(arg0), index*(24+4*4))
		value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)))
		value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (16 + 2*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (16 + 3*4))))

		result = append(result, portfolio_value_valuation.Event{ItemId: value, Kind: uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (2 * 4))))), Quantity: uint32(*(*int32)(unsafe.Add(unsafe.Pointer(base), (4 + 2*4)))), UnitMinor: *(*int64)(unsafe.Add(unsafe.Pointer(base), (8 + 2*4))), Currency: value0, At: uint64(*(*int64)(unsafe.Add(unsafe.Pointer(base), (16 + 4*4))))})
	}

	result3 := make([]portfolio_value_valuation.Quote, 0, arg3)
	for index := 0; index < int(arg3); index++ {
		base := unsafe.Add(unsafe.Pointer(arg2), index*(16+4*4))
		value1 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)))
		value2 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 2*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 3*4))))

		result3 = append(result3, portfolio_value_valuation.Quote{ItemId: value1, UnitMinor: *(*int64)(unsafe.Add(unsafe.Pointer(base), (2 * 4))), Currency: value2, At: uint64(*(*int64)(unsafe.Add(unsafe.Pointer(base), (8 + 4*4))))})
	}

	witRuntime.Unpin()
	result4 := export_portfolio_value_valuation.Series(result, result3, uint64(arg4), uint64(arg5), uint64(arg6))

	switch result4.Tag() {
	case witTypes.ResultOk:
		payload := result4.Ok()
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(0))
		slice := payload
		length := uint32(len(slice))
		result5 := witRuntime.Allocate(pinner, uintptr(length*40), 8)
		for index, element := range slice {
			base := unsafe.Add(result5, index*40)
			*(*int64)(unsafe.Add(unsafe.Pointer(base), 0)) = int64((element).At)
			*(*int64)(unsafe.Add(unsafe.Pointer(base), 8)) = (element).MarketValueMinor
			*(*int64)(unsafe.Add(unsafe.Pointer(base), 16)) = (element).CostBasisMinor
			*(*int64)(unsafe.Add(unsafe.Pointer(base), 24)) = (element).RealisedMinor
			*(*int32)(unsafe.Add(unsafe.Pointer(base), 32)) = int32((element).Unquoted)

		}

		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (8 + 1*4))) = uint32(length)
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 8)) = uint32(uintptr(uintptr(result5)))

	case witTypes.ResultErr:
		payload := result4.Err()
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(1))

		switch payload.Tag() {
		case portfolio_value_valuation.ValueErrorMixedCurrency:
			payload := payload.MixedCurrency()
			*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 8)) = int8(int32(0))
			utf8 := unsafe.Pointer(unsafe.StringData((payload).F0))
			pinner.Pin(utf8)
			*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (16 + 1*4))) = uint32(uint32(len((payload).F0)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 16)) = uint32(uintptr(uintptr(utf8)))
			utf86 := unsafe.Pointer(unsafe.StringData((payload).F1))
			pinner.Pin(utf86)
			*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (16 + 3*4))) = uint32(uint32(len((payload).F1)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (16 + 2*4))) = uint32(uintptr(uintptr(utf86)))

		case portfolio_value_valuation.ValueErrorOversoldAt:
			payload := payload.OversoldAt()
			*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 8)) = int8(int32(1))
			utf87 := unsafe.Pointer(unsafe.StringData((payload).F0))
			pinner.Pin(utf87)
			*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (16 + 1*4))) = uint32(uint32(len((payload).F0)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 16)) = uint32(uintptr(uintptr(utf87)))
			*(*int64)(unsafe.Add(unsafe.Pointer(exportReturnArea), (16 + 2*4))) = int64((payload).F1)
			*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (24 + 2*4))) = int32((payload).F2)
			*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (28 + 2*4))) = int32((payload).F3)

		case portfolio_value_valuation.ValueErrorZeroQuantity:
			payload := payload.ZeroQuantity()
			*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 8)) = int8(int32(2))
			utf88 := unsafe.Pointer(unsafe.StringData((payload).F0))
			pinner.Pin(utf88)
			*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (16 + 1*4))) = uint32(uint32(len((payload).F0)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 16)) = uint32(uintptr(uintptr(utf88)))
			*(*int64)(unsafe.Add(unsafe.Pointer(exportReturnArea), (16 + 2*4))) = int64((payload).F1)

		case portfolio_value_valuation.ValueErrorZeroStep:

			*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 8)) = int8(int32(3))

		case portfolio_value_valuation.ValueErrorEmpty:

			*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 8)) = int8(int32(4))

		default:
			panic("unreachable")
		}

	default:
		panic("unreachable")
	}
	return exportReturnArea

}

//go:wasmexport cabi_post_portfolio:value/valuation@0.1.0#series
func wasm_export_post_return_portfolio_value_valuation_series(result uintptr) {
	syncExportPinner.Unpin()
}

// Unused, but present to make the compiler happy
func main() {}
