# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
from ..exports import history

class History(Protocol):

    @abstractmethod
    def at(self, quotes: List[history.Quote], kind: history.QuoteKind, at: int) -> history.Observed:
        """
        The latest quote of `kind` at or before `at`, carried forward if older.
        
        Two sources at one instant resolve newest-first, then by source name, so the
        answer does not depend on the order they were fetched in.
        
        Raises: `componentize_py_types.Err(wit_world.imports.history.PriceError)`
        """
        raise NotImplementedError

    @abstractmethod
    def series(self, quotes: List[history.Quote], kind: history.QuoteKind, since: int, until: int, step: int) -> List[history.Point]:
        """
        The series over `since`..=`until`, sampled every `step` seconds.
        
        A gap CARRIES THE LAST PRICE FORWARD and never interpolates: a market has no
        price on a day nobody traded, and a straight line across a quiet week invents
        most of a five-year chart. Samples before the first quote are ABSENT rather
        than zero, so an empty result means "never priced in this window".
        
        Raises: `componentize_py_types.Err(wit_world.imports.history.PriceError)`
        """
        raise NotImplementedError


