# This file is automatically generated by componentize-py
# It is not intended for manual editing.
"""
What a price was, at an instant and across a window.
"""
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some


class QuoteKind(Enum):
    """
    Which number a source was asked for. A market price and a lowest listing are
    different questions, one systematically below the other, and a series that
    mixes them is answering neither.
    """
    MARKET = 0
    LOW = 1
    HIGH = 2
    LAST_SOLD = 3

@dataclass
class Quote:
    """
    One observation of a price.
    """
    unit_minor: int
    currency: str
    kind: QuoteKind
    source: str
    at: int

@dataclass
class Observed:
    """
    A price at an instant, and how much to trust it.
    """
    unit_minor: int
    currency: str
    source: str
    observed_at: int
    age_seconds: int
    carried: bool

@dataclass
class Point:
    """
    One sample on a price chart.
    """
    at: int
    unit_minor: int
    carried: bool


@dataclass
class PriceError_NotYetPriced:
    pass


@dataclass
class PriceError_MixedCurrency:
    value: Tuple[str, str]


@dataclass
class PriceError_ZeroStep:
    pass


PriceError = Union[PriceError_NotYetPriced, PriceError_MixedCurrency, PriceError_ZeroStep]
"""
Why a lookup produced nothing.
"""


