[package]
name = "mail-parse"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
mailparse = "0.16.1"
wit-bindgen-rt = { workspace = true, features = ["bitflags"] }

[lib]
crate-type = ["cdylib"]

[package.metadata.component]
package = "component:mail-parse"

[package.metadata.component.dependencies]
