// Generated by `wit-bindgen` 0.61.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     wasi:io@0.2.0
//     wasi:cli@0.2.0
//     wasi:clocks@0.2.0
//     wasi:random@0.2.0
//     portfolio:value@0.1.0

package wasi_cli_stderr

import (
	"wit_component/wasi_io_streams"
)

type OutputStream = wasi_io_streams.OutputStream

//go:wasmimport wasi:cli/stderr@0.2.0 get-stderr
func wasm_import_get_stderr() int32

func GetStderr() *wasi_io_streams.OutputStream {

	result := wasm_import_get_stderr()
	return wasi_io_streams.OutputStreamFromOwnHandle(int32(uintptr(result)))

}
