//! `static-assets` — serve an embedded static bundle — an SPA in a component of its own, so the domain artifact stays slim
//!
//! The built React SPA embedded at build time (build.rs walks `static/` and
//! `include_bytes!`s every file). Exists so the HTTP-facing domain component
//! stays slim — it links this capability for `GET /`, `/assets/*` etc. instead
//! of carrying ~620 KB of UI in its own artifact, which inflates per-request
//! instantiation on hosts that instantiate per request (wasmCloud).
//!
//! Pure compute: exact-path lookup over a static table. No imports, no state.

#[allow(warnings)]
mod bindings;

// STATIC_ASSETS: &[(web_path, content_type, bytes)], generated by build.rs.
mod static_assets {
    include!(concat!(env!("OUT_DIR"), "/static_assets.rs"));
}

use bindings::exports::ui::assets::files::{Asset, Guest};

struct Component;

impl Guest for Component {
    fn get(path: String) -> Option<Asset> {
        static_assets::STATIC_ASSETS
            .iter()
            .find(|(p, _, _)| *p == path)
            .map(|(_, ct, bytes)| Asset {
                content_type: (*ct).to_string(),
                body: bytes.to_vec(),
            })
    }
}

bindings::export!(Component with_types_in bindings);
