#!/usr/bin/env python3
"""Derive `apps/<name>.toml` from the `host-<app>` recipes that already run each app.

The tier-1 spec (docs/SELFHOST.md) is meant to be the only hand-authored file in
the lane, and it is — but writing fifty of them by hand would be transcribing
what the Justfile already says. Every `host-<app>` recipe names the composed
artifact, the port and the SPA directory, because that is what it takes to run
the app locally; a spec is those three facts plus a hostname.

So this reads them rather than a person re-typing them. What it CANNOT know is
the hostname and the access mode, and it must not guess: `access` is left at its
default (tailnet, fail-closed) and `domain` is `<name>.example.com`, which is a
placeholder a person is expected to edit. A generated file that quietly picked a
real domain would be worse than one that obviously did not.

An existing spec is never overwritten — this fills gaps, it does not own the
directory.

  python3 tools/gen-app-specs.py            # write missing specs
  python3 tools/gen-app-specs.py --dry-run  # print what it would write
"""

import argparse
import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Recipes that are `host-*` but are not an app being served:
#   platform  — the whole local control plane (NATS + reconciler + node), not an app
#   nats/redis/full — the vet-clinic under a different --kv, i.e. the same app thrice
#   console   — the operator surface for a running platform, not a showcase app
#   eshop     — no --component; it is the wasmCloud/k8s lane
NOT_APPS = {"platform", "nats", "redis", "full", "console", "eshop"}

# Ports more than one `host-*` recipe uses. Two apps may share a port locally —
# only one is ever running — but two SPECS may not, and `node validate` says so.
# Carrying no port is the better answer than inventing one: the renderer derives
# a stable port from the name, which is unique by construction.
#
# Computed rather than listed, so a new collision in the Justfile is handled
# rather than discovered at validate time.
def shared_ports(recipes_):
    seen = {}
    for name, body in recipes_.items():
        if name in NOT_APPS:
            continue
        m = re.search(r"--addr \S*?:(\d+)", body)
        if m:
            seen.setdefault(m.group(1), []).append(name)
    return {p for p, who in seen.items() if len(who) > 1}


def just_vars():
    """Every `name := "value"` the Justfile defines, already resolved."""
    out = subprocess.run(
        ["just", "--evaluate"], cwd=ROOT, capture_output=True, text=True, check=True
    ).stdout
    vars_ = {}
    for line in out.splitlines():
        m = re.match(r'^(\S+)\s*:=\s*"(.*)"\s*$', line)
        if m:
            vars_[m.group(1)] = m.group(2)
    return vars_


def recipes():
    """`host-<app>` recipe bodies, as one flattened string each."""
    lines = open(os.path.join(ROOT, "Justfile")).read().split("\n")
    found = {}
    i = 0
    while i < len(lines):
        m = re.match(r"^host-([a-z0-9-]+):", lines[i])
        if not m:
            i += 1
            continue
        body, j = [], i + 1
        while j < len(lines) and (lines[j].startswith((" ", "\t")) or not lines[j].strip()):
            if lines[j].strip():
                body.append(lines[j].strip())
            j += 1
        found[m.group(1)] = " ".join(body)
        i = j
    return found


def expand(value, vars_):
    """Resolve `{{ var }}` against the Justfile's own definitions."""
    return re.sub(r"\{\{\s*(\w+)\s*\}\}", lambda m: vars_.get(m.group(1), m.group(0)), value)


def spec_for(name, body, vars_, shared):
    art = re.search(r"--component \.\./?(\S+)", body)
    if not art:
        return None
    artifact = expand(art.group(1), vars_)
    if "{{" in artifact:
        return None

    port = re.search(r"--addr \S*?:(\d+)", body)
    static = re.search(r"--static-dir \.\./?(\S+)", body)

    s = [
        "# Generated by tools/gen-app-specs.py from this app's `host-%s` recipe." % name,
        "# EDIT `domain` before deploying — the value below is a placeholder.",
        "#",
        "#   just selfhost-render %s            # read the unit and route first" % name,
        "#   just selfhost-deploy %s my-vps     # compose, ship, restart, route" % name,
        'name = "%s"' % name,
        "# tailnet is the default and is left alone on purpose: a generated file must",
        "# never be the reason an app is reachable from the internet. Set",
        '# access = "public" deliberately, per app.',
        'domain = "%s.example.com"' % name,
        'artifact = "%s"' % artifact,
    ]
    if port and port.group(1) not in shared:
        s.append("# The port this app is run on locally, kept so a deployed app matches the")
        s.append("# recipe. Omit it and one is derived from the name, stably.")
        s.append("port = %s" % port.group(1))
    if static:
        s.append('static_dir = "%s"' % expand(static.group(1), vars_))
    s.append("")
    s.append("# sqlite: one file under the unit's StateDirectory, so state survives the")
    s.append("# restarts `Restart=always` makes routine.")
    s.append('kv = "sqlite"')
    return "\n".join(s) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    vars_ = just_vars()
    found = recipes()
    shared = shared_ports(found)
    apps = os.path.join(ROOT, "apps")
    os.makedirs(apps, exist_ok=True)

    wrote, skipped, kept = [], [], []
    for name, body in sorted(found.items()):
        if name in NOT_APPS:
            continue
        text = spec_for(name, body, vars_, shared)
        if text is None:
            skipped.append(name)
            continue
        path = os.path.join(apps, name + ".toml")
        if os.path.exists(path):
            kept.append(name)
            continue
        if args.dry_run:
            print("--- apps/%s.toml ---\n%s" % (name, text))
        else:
            open(path, "w").write(text)
        wrote.append(name)

    verb = "would write" if args.dry_run else "wrote"
    print("%s %d spec(s): %s" % (verb, len(wrote), " ".join(wrote)), file=sys.stderr)
    if kept:
        print("kept %d existing: %s" % (len(kept), " ".join(kept)), file=sys.stderr)
    if skipped:
        print("skipped %d (no resolvable --component): %s" % (len(skipped), " ".join(skipped)),
              file=sys.stderr)


if __name__ == "__main__":
    main()
