[package]
name = "assignment"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
guestfmt = { path = "../guestfmt" }
guestio = { path = "../guestio" }
wit-bindgen-rt = { workspace = true, features = ["bitflags"] }
serde = { workspace = true }
serde_json = { workspace = true }

[lib]
crate-type = ["cdylib"]

[package.metadata.component]
package = "component:assignment"

[package.metadata.component.target]
path = "wit"
world = "assignment-router"

[package.metadata.component.target.dependencies]
"event:bus" = { path = "../event-bus/wit" }
"records:store" = { path = "../record-store/wit" }
"wasi:http" = { path = "../../wit/deps/wasi-http-0.2.0" }
"wasi:io" = { path = "../../wit/deps/wasi-io-0.2.0" }
"wasi:clocks" = { path = "../../wit/deps/wasi-clocks-0.2.0" }
"wasi:cli" = { path = "../../wit/deps/wasi-cli-0.2.0" }
"wasi:random" = { path = "../../wit/deps/wasi-random-0.2.0" }
"wasi:keyvalue" = { path = "../../wit/deps/wasi-keyvalue-0.2.0-draft" }
"comp:store" = { path = "../../host/wit/deps/comp-store" }
