[package]
name = "assignment"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
guestfmt = { path = "../guestfmt" }
guestio = { path = "../guestio" }
wit-bindgen = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[lib]
crate-type = ["cdylib"]
