// Generated by `wit-bindgen` 0.61.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     wasi:io@0.2.0
//     wasi:cli@0.2.0
//     wasi:clocks@0.2.0
//     wasi:random@0.2.0
//     price:history@0.1.0

package price_history_history

import (
	witTypes "go.bytecodealliance.org/pkg/wit/types"
)

const (
	// What copies are actually changing hands at.
	QuoteKindMarket uint8 = 0
	// The cheapest current listing.
	QuoteKindLow uint8 = 1
	// The dearest current listing.
	QuoteKindHigh uint8 = 2
	// The last completed sale.
	QuoteKindLastSold uint8 = 3
)

// Which number a source was asked for. A market price and a lowest listing are
// different questions, one systematically below the other, and a series that
// mixes them is answering neither.
type QuoteKind = uint8

// One observation of a price.
type Quote struct {
	UnitMinor int64
	// ISO-4217, compared exactly and never converted.
	Currency string
	Kind     QuoteKind
	// Where it came from. Two sources may disagree about one instant, and
	// resolving that needs to know which is which.
	Source string
	// Unix seconds observed.
	At uint64
}

// A price at an instant, and how much to trust it.
type Observed struct {
	UnitMinor int64
	Currency  string
	Source    string
	// When the underlying quote was observed — NOT the instant asked about.
	ObservedAt uint64
	// How old the quote was at the instant asked about. Zero means it was
	// observed exactly then. A four-month-old quote is the best information
	// available and also barely information; it is returned WITH its age
	// rather than refused or passed off as fresh.
	AgeSeconds uint64
	// True when this is a previous quote carried forward across a gap.
	Carried bool
}

// One sample on a price chart.
type Point struct {
	At        uint64
	UnitMinor int64
	// Carried forward rather than observed here. A caller that wants to draw a
	// carried segment differently has what it needs; one that ignores this is
	// still not lied to.
	Carried bool
}

const (
	// No quote of this kind at or before the instant. DISTINCT from a price of
	// zero: a chart that starts at zero and jumps shows a gain nobody made.
	PriceErrorNotYetPriced uint8 = 0
	// Quotes in more than one currency. Refused, never converted. Carries
	// expected and found.
	PriceErrorMixedCurrency uint8 = 1
	// A step of zero does not terminate.
	PriceErrorZeroStep uint8 = 2
)

// Why a lookup produced nothing.
type PriceError struct {
	tag   uint8
	value any
}

func (self PriceError) Tag() uint8 {
	return self.tag
}

func (self PriceError) MixedCurrency() witTypes.Tuple2[string, string] {
	if self.tag != PriceErrorMixedCurrency {
		panic("tag mismatch")
	}
	return self.value.(witTypes.Tuple2[string, string])
}

func MakePriceErrorNotYetPriced() PriceError {
	return PriceError{PriceErrorNotYetPriced, nil}
}
func MakePriceErrorMixedCurrency(value witTypes.Tuple2[string, string]) PriceError {
	return PriceError{PriceErrorMixedCurrency, value}
}
func MakePriceErrorZeroStep() PriceError {
	return PriceError{PriceErrorZeroStep, nil}
}
