//! First-time setup: generates the appservice tokens, logs the owner in once (to get
//! the session token used to accept the owner's invites), and writes the
//! config and the registration file Synapse needs. Nothing here is committed.

use std::io::Read;
use std::path::{Path, PathBuf};

use serde_json::json;

use crate::config::{write_private, Config};

pub struct InitArgs {
    pub server_name: String,
    pub homeserver: String,
    pub owner_localpart: String,
    pub owner_password: String,
    pub runtime_url: String,
    pub runtime_token: String,
    pub listen: String,
    /// The URL SYNAPSE uses to reach this bridge (may differ from `listen`).
    pub appservice_url: String,
    pub dir: PathBuf,
}

fn random_hex(bytes: usize) -> Result<String, String> {
    let mut buf = vec![0u8; bytes];
    std::fs::File::open("/dev/urandom")
        .and_then(|mut f| f.read_exact(&mut buf))
        .map_err(|e| format!("reading /dev/urandom: {e}"))?;
    Ok(buf.iter().map(|b| format!("{b:02x}")).collect())
}

fn login(homeserver: &str, user: &str, password: &str) -> Result<String, String> {
    let r = reqwest::blocking::Client::new()
        .post(format!("{}/_matrix/client/v3/login", homeserver.trim_end_matches('/')))
        .json(&json!({
            "type": "m.login.password",
            "identifier": {"type": "m.id.user", "user": user},
            "password": password,
            "initial_device_display_name": "holon-bridge",
        }))
        .send()
        .map_err(|e| format!("could not reach {homeserver}: {e}"))?;
    let status = r.status();
    let v: serde_json::Value = r.json().map_err(|e| e.to_string())?;
    v["access_token"]
        .as_str()
        .map(String::from)
        .ok_or_else(|| format!("login failed ({status}): {v}"))
}

/// The registration file Synapse loads (`app_service_config_files`).
pub fn registration_yaml(cfg: &Config, appservice_url: &str) -> String {
    format!(
        "# Generated by `agent-matrix init`. Contains secrets: keep it private.\n\
         id: holon-agents\n\
         url: {appservice_url}\n\
         as_token: {}\n\
         hs_token: {}\n\
         sender_localpart: holon-bridge\n\
         rate_limited: false\n\
         namespaces:\n  \
           users:\n    \
             - exclusive: true\n      \
               regex: '@agent-.*:{}'\n  \
           aliases: []\n  \
           rooms: []\n",
        cfg.as_token,
        cfg.hs_token,
        cfg.server_name.replace('.', "\\.")
    )
}

pub fn init(a: InitArgs) -> Result<(PathBuf, PathBuf), String> {
    std::fs::create_dir_all(&a.dir).map_err(|e| format!("{}: {e}", a.dir.display()))?;
    let owner = format!("@{}:{}", a.owner_localpart, a.server_name);
    let admin_token = login(&a.homeserver, &a.owner_localpart, &a.owner_password)?;
    let cfg = Config {
        homeserver: a.homeserver,
        server_name: a.server_name,
        as_token: random_hex(32)?,
        hs_token: random_hex(32)?,
        listen: a.listen,
        runtime_url: a.runtime_url,
        runtime_token: a.runtime_token,
        owner,
        admin_token,
        state_file: a.dir.join("state.json"),
    };
    let config_path = a.dir.join("bridge.json");
    let reg_path = a.dir.join("holon-agents.yaml");
    cfg.save(&config_path)?;
    write_private(&reg_path, &registration_yaml(&cfg, &a.appservice_url))?;
    Ok((config_path, reg_path))
}

/// Used by tests and `main` to read the runtime's admin token from its state dir.
pub fn read_token(path: &Path) -> Result<String, String> {
    std::fs::read_to_string(path)
        .map(|s| s.trim().to_string())
        .map_err(|e| format!("{}: {e}", path.display()))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_registration_claims_exactly_the_agent_namespace_and_carries_both_tokens() {
        let cfg = Config {
            homeserver: "http://x".into(),
            server_name: "malna.tail3a9c.ts.net".into(),
            as_token: "AS".into(),
            hs_token: "HS".into(),
            listen: "0.0.0.0:9009".into(),
            runtime_url: "http://r".into(),
            runtime_token: "t".into(),
            owner: "@mark:malna.tail3a9c.ts.net".into(),
            admin_token: "x".into(),
            state_file: "/tmp/s".into(),
        };
        let y = registration_yaml(&cfg, "http://100.81.10.8:9009");
        assert!(y.contains("url: http://100.81.10.8:9009"));
        assert!(y.contains("as_token: AS") && y.contains("hs_token: HS"));
        assert!(y.contains(r"regex: '@agent-.*:malna\.tail3a9c\.ts\.net'"), "{y}");
        assert!(y.contains("exclusive: true") && y.contains("sender_localpart: holon-bridge"));
        assert!(y.contains("aliases: []"), "no aliases are claimed");
    }

    #[test]
    fn random_tokens_differ() {
        assert_ne!(random_hex(16).unwrap(), random_hex(16).unwrap());
        assert_eq!(random_hex(32).unwrap().len(), 64);
    }
}
